PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.12.7'

inputs:
- name: gpupgrade_src
  path: ../../../go/src/github.com/greenplum-db/gpupgrade

outputs:
  - name: gpupgrade_bin_path

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cd $GOPATH/src/github.com/greenplum-db/gpupgrade
      make depend
      make

      # todo: is there a cleaner way to get this format?
      version=$(git describe | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/')
    cd -

    cp $GOPATH/src/github.com/greenplum-db/gpupgrade/gpupgrade gpupgrade_bin_path/gpupgrade-rc-$version-linux_x86_64
