# Copyright (c) 2017-2020 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: "7-gcc6.2-llvm3.7"

inputs:
- name: gpupgrade_src
  path: go/src/github.com/greenplum-db/gpupgrade
- name: gpdb_src_source
- name: gpdb_src_target
- name: rpm_gpdb_source
- name: rpm_gpdb_target
- name: bats

run:
  path: go/src/github.com/greenplum-db/gpupgrade/ci/scripts/install-tests.bash
