PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-test
    tag: latest

inputs:
  - name: gpupgrade_src
    path: go/src/github.com/greenplum-db/gpupgrade
  - name: retail_demo_src
  - name: ccp_src
  - name: cluster_env_files

run:
  path: go/src/github.com/greenplum-db/gpupgrade/ci/scripts/load-retail-data.bash

params:
  OLD_PACKAGE:
  NEW_PACKAGE:
