// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cli_to_hub.proto

package idl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpgradeSteps int32

const (
	UpgradeSteps_UNKNOWN_STEP            UpgradeSteps = 0
	UpgradeSteps_CONFIG                  UpgradeSteps = 1
	UpgradeSteps_START_AGENTS            UpgradeSteps = 2
	UpgradeSteps_CREATE_TARGET_CONFIG    UpgradeSteps = 3
	UpgradeSteps_SHUTDOWN_SOURCE_CLUSTER UpgradeSteps = 4
	UpgradeSteps_INIT_TARGET_CLUSTER     UpgradeSteps = 5
	UpgradeSteps_SHUTDOWN_TARGET_CLUSTER UpgradeSteps = 6
	UpgradeSteps_UPGRADE_MASTER          UpgradeSteps = 7
	UpgradeSteps_COPY_MASTER             UpgradeSteps = 8
	UpgradeSteps_UPGRADE_PRIMARIES       UpgradeSteps = 9
	UpgradeSteps_START_TARGET_CLUSTER    UpgradeSteps = 10
	UpgradeSteps_RECONFIGURE_PORTS       UpgradeSteps = 11
)

var UpgradeSteps_name = map[int32]string{
	0:  "UNKNOWN_STEP",
	1:  "CONFIG",
	2:  "START_AGENTS",
	3:  "CREATE_TARGET_CONFIG",
	4:  "SHUTDOWN_SOURCE_CLUSTER",
	5:  "INIT_TARGET_CLUSTER",
	6:  "SHUTDOWN_TARGET_CLUSTER",
	7:  "UPGRADE_MASTER",
	8:  "COPY_MASTER",
	9:  "UPGRADE_PRIMARIES",
	10: "START_TARGET_CLUSTER",
	11: "RECONFIGURE_PORTS",
}
var UpgradeSteps_value = map[string]int32{
	"UNKNOWN_STEP":            0,
	"CONFIG":                  1,
	"START_AGENTS":            2,
	"CREATE_TARGET_CONFIG":    3,
	"SHUTDOWN_SOURCE_CLUSTER": 4,
	"INIT_TARGET_CLUSTER":     5,
	"SHUTDOWN_TARGET_CLUSTER": 6,
	"UPGRADE_MASTER":          7,
	"COPY_MASTER":             8,
	"UPGRADE_PRIMARIES":       9,
	"START_TARGET_CLUSTER":    10,
	"RECONFIGURE_PORTS":       11,
}

func (x UpgradeSteps) String() string {
	return proto.EnumName(UpgradeSteps_name, int32(x))
}
func (UpgradeSteps) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{0}
}

type StepStatus int32

const (
	StepStatus_UNKNOWN_STATUS StepStatus = 0
	StepStatus_PENDING        StepStatus = 1
	StepStatus_RUNNING        StepStatus = 2
	StepStatus_COMPLETE       StepStatus = 3
	StepStatus_FAILED         StepStatus = 4
)

var StepStatus_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "PENDING",
	2: "RUNNING",
	3: "COMPLETE",
	4: "FAILED",
}
var StepStatus_value = map[string]int32{
	"UNKNOWN_STATUS": 0,
	"PENDING":        1,
	"RUNNING":        2,
	"COMPLETE":       3,
	"FAILED":         4,
}

func (x StepStatus) String() string {
	return proto.EnumName(StepStatus_name, int32(x))
}
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{1}
}

type Chunk_Type int32

const (
	Chunk_UNKNOWN Chunk_Type = 0
	Chunk_STDOUT  Chunk_Type = 1
	Chunk_STDERR  Chunk_Type = 2
)

var Chunk_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "STDOUT",
	2: "STDERR",
}
var Chunk_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"STDOUT":  1,
	"STDERR":  2,
}

func (x Chunk_Type) String() string {
	return proto.EnumName(Chunk_Type_name, int32(x))
}
func (Chunk_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{14, 0}
}

type InitializeRequest struct {
	OldBinDir            string   `protobuf:"bytes,1,opt,name=oldBinDir" json:"oldBinDir,omitempty"`
	NewBinDir            string   `protobuf:"bytes,2,opt,name=newBinDir" json:"newBinDir,omitempty"`
	OldPort              int32    `protobuf:"varint,3,opt,name=oldPort" json:"oldPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeRequest) Reset()         { *m = InitializeRequest{} }
func (m *InitializeRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeRequest) ProtoMessage()    {}
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{0}
}
func (m *InitializeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeRequest.Unmarshal(m, b)
}
func (m *InitializeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeRequest.Marshal(b, m, deterministic)
}
func (dst *InitializeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeRequest.Merge(dst, src)
}
func (m *InitializeRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeRequest.Size(m)
}
func (m *InitializeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeRequest proto.InternalMessageInfo

func (m *InitializeRequest) GetOldBinDir() string {
	if m != nil {
		return m.OldBinDir
	}
	return ""
}

func (m *InitializeRequest) GetNewBinDir() string {
	if m != nil {
		return m.NewBinDir
	}
	return ""
}

func (m *InitializeRequest) GetOldPort() int32 {
	if m != nil {
		return m.OldPort
	}
	return 0
}

type ExecuteRequest struct {
	Ports                []uint32 `protobuf:"varint,1,rep,packed,name=ports" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{1}
}
func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (dst *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(dst, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetPorts() []uint32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

type FinalizeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeRequest) Reset()         { *m = FinalizeRequest{} }
func (m *FinalizeRequest) String() string { return proto.CompactTextString(m) }
func (*FinalizeRequest) ProtoMessage()    {}
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{2}
}
func (m *FinalizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeRequest.Unmarshal(m, b)
}
func (m *FinalizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeRequest.Marshal(b, m, deterministic)
}
func (dst *FinalizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeRequest.Merge(dst, src)
}
func (m *FinalizeRequest) XXX_Size() int {
	return xxx_messageInfo_FinalizeRequest.Size(m)
}
func (m *FinalizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeRequest proto.InternalMessageInfo

type RestartAgentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartAgentsRequest) Reset()         { *m = RestartAgentsRequest{} }
func (m *RestartAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*RestartAgentsRequest) ProtoMessage()    {}
func (*RestartAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{3}
}
func (m *RestartAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartAgentsRequest.Unmarshal(m, b)
}
func (m *RestartAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartAgentsRequest.Marshal(b, m, deterministic)
}
func (dst *RestartAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartAgentsRequest.Merge(dst, src)
}
func (m *RestartAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_RestartAgentsRequest.Size(m)
}
func (m *RestartAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartAgentsRequest proto.InternalMessageInfo

type RestartAgentsReply struct {
	AgentHosts           []string `protobuf:"bytes,1,rep,name=agentHosts" json:"agentHosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartAgentsReply) Reset()         { *m = RestartAgentsReply{} }
func (m *RestartAgentsReply) String() string { return proto.CompactTextString(m) }
func (*RestartAgentsReply) ProtoMessage()    {}
func (*RestartAgentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{4}
}
func (m *RestartAgentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartAgentsReply.Unmarshal(m, b)
}
func (m *RestartAgentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartAgentsReply.Marshal(b, m, deterministic)
}
func (dst *RestartAgentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartAgentsReply.Merge(dst, src)
}
func (m *RestartAgentsReply) XXX_Size() int {
	return xxx_messageInfo_RestartAgentsReply.Size(m)
}
func (m *RestartAgentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartAgentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_RestartAgentsReply proto.InternalMessageInfo

func (m *RestartAgentsReply) GetAgentHosts() []string {
	if m != nil {
		return m.AgentHosts
	}
	return nil
}

type StopServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServicesRequest) Reset()         { *m = StopServicesRequest{} }
func (m *StopServicesRequest) String() string { return proto.CompactTextString(m) }
func (*StopServicesRequest) ProtoMessage()    {}
func (*StopServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{5}
}
func (m *StopServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServicesRequest.Unmarshal(m, b)
}
func (m *StopServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServicesRequest.Marshal(b, m, deterministic)
}
func (dst *StopServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServicesRequest.Merge(dst, src)
}
func (m *StopServicesRequest) XXX_Size() int {
	return xxx_messageInfo_StopServicesRequest.Size(m)
}
func (m *StopServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopServicesRequest proto.InternalMessageInfo

type StopServicesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServicesReply) Reset()         { *m = StopServicesReply{} }
func (m *StopServicesReply) String() string { return proto.CompactTextString(m) }
func (*StopServicesReply) ProtoMessage()    {}
func (*StopServicesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{6}
}
func (m *StopServicesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServicesReply.Unmarshal(m, b)
}
func (m *StopServicesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServicesReply.Marshal(b, m, deterministic)
}
func (dst *StopServicesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServicesReply.Merge(dst, src)
}
func (m *StopServicesReply) XXX_Size() int {
	return xxx_messageInfo_StopServicesReply.Size(m)
}
func (m *StopServicesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServicesReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopServicesReply proto.InternalMessageInfo

type UpgradeStepStatus struct {
	Step                 UpgradeSteps `protobuf:"varint,1,opt,name=step,enum=idl.UpgradeSteps" json:"step,omitempty"`
	Status               StepStatus   `protobuf:"varint,2,opt,name=status,enum=idl.StepStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpgradeStepStatus) Reset()         { *m = UpgradeStepStatus{} }
func (m *UpgradeStepStatus) String() string { return proto.CompactTextString(m) }
func (*UpgradeStepStatus) ProtoMessage()    {}
func (*UpgradeStepStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{7}
}
func (m *UpgradeStepStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeStepStatus.Unmarshal(m, b)
}
func (m *UpgradeStepStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeStepStatus.Marshal(b, m, deterministic)
}
func (dst *UpgradeStepStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeStepStatus.Merge(dst, src)
}
func (m *UpgradeStepStatus) XXX_Size() int {
	return xxx_messageInfo_UpgradeStepStatus.Size(m)
}
func (m *UpgradeStepStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeStepStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeStepStatus proto.InternalMessageInfo

func (m *UpgradeStepStatus) GetStep() UpgradeSteps {
	if m != nil {
		return m.Step
	}
	return UpgradeSteps_UNKNOWN_STEP
}

func (m *UpgradeStepStatus) GetStatus() StepStatus {
	if m != nil {
		return m.Status
	}
	return StepStatus_UNKNOWN_STATUS
}

type CheckVersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionRequest) Reset()         { *m = CheckVersionRequest{} }
func (m *CheckVersionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVersionRequest) ProtoMessage()    {}
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{8}
}
func (m *CheckVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionRequest.Unmarshal(m, b)
}
func (m *CheckVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionRequest.Marshal(b, m, deterministic)
}
func (dst *CheckVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionRequest.Merge(dst, src)
}
func (m *CheckVersionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVersionRequest.Size(m)
}
func (m *CheckVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionRequest proto.InternalMessageInfo

type CheckVersionReply struct {
	IsVersionCompatible  bool     `protobuf:"varint,1,opt,name=IsVersionCompatible" json:"IsVersionCompatible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionReply) Reset()         { *m = CheckVersionReply{} }
func (m *CheckVersionReply) String() string { return proto.CompactTextString(m) }
func (*CheckVersionReply) ProtoMessage()    {}
func (*CheckVersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{9}
}
func (m *CheckVersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionReply.Unmarshal(m, b)
}
func (m *CheckVersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionReply.Marshal(b, m, deterministic)
}
func (dst *CheckVersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionReply.Merge(dst, src)
}
func (m *CheckVersionReply) XXX_Size() int {
	return xxx_messageInfo_CheckVersionReply.Size(m)
}
func (m *CheckVersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionReply proto.InternalMessageInfo

func (m *CheckVersionReply) GetIsVersionCompatible() bool {
	if m != nil {
		return m.IsVersionCompatible
	}
	return false
}

type CheckDiskSpaceRequest struct {
	Ratio                float32  `protobuf:"fixed32,1,opt,name=ratio" json:"ratio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckDiskSpaceRequest) Reset()         { *m = CheckDiskSpaceRequest{} }
func (m *CheckDiskSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceRequest) ProtoMessage()    {}
func (*CheckDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{10}
}
func (m *CheckDiskSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceRequest.Unmarshal(m, b)
}
func (m *CheckDiskSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceRequest.Marshal(b, m, deterministic)
}
func (dst *CheckDiskSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceRequest.Merge(dst, src)
}
func (m *CheckDiskSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceRequest.Size(m)
}
func (m *CheckDiskSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceRequest proto.InternalMessageInfo

func (m *CheckDiskSpaceRequest) GetRatio() float32 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

type CheckDiskSpaceReply struct {
	Failed               map[string]*CheckDiskSpaceReply_DiskUsage `protobuf:"bytes,1,rep,name=failed" json:"failed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *CheckDiskSpaceReply) Reset()         { *m = CheckDiskSpaceReply{} }
func (m *CheckDiskSpaceReply) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceReply) ProtoMessage()    {}
func (*CheckDiskSpaceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{11}
}
func (m *CheckDiskSpaceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceReply.Unmarshal(m, b)
}
func (m *CheckDiskSpaceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceReply.Marshal(b, m, deterministic)
}
func (dst *CheckDiskSpaceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceReply.Merge(dst, src)
}
func (m *CheckDiskSpaceReply) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceReply.Size(m)
}
func (m *CheckDiskSpaceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceReply proto.InternalMessageInfo

func (m *CheckDiskSpaceReply) GetFailed() map[string]*CheckDiskSpaceReply_DiskUsage {
	if m != nil {
		return m.Failed
	}
	return nil
}

type CheckDiskSpaceReply_DiskUsage struct {
	Available            uint64   `protobuf:"varint,1,opt,name=available" json:"available,omitempty"`
	Required             uint64   `protobuf:"varint,2,opt,name=required" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckDiskSpaceReply_DiskUsage) Reset()         { *m = CheckDiskSpaceReply_DiskUsage{} }
func (m *CheckDiskSpaceReply_DiskUsage) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceReply_DiskUsage) ProtoMessage()    {}
func (*CheckDiskSpaceReply_DiskUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{11, 0}
}
func (m *CheckDiskSpaceReply_DiskUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceReply_DiskUsage.Unmarshal(m, b)
}
func (m *CheckDiskSpaceReply_DiskUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceReply_DiskUsage.Marshal(b, m, deterministic)
}
func (dst *CheckDiskSpaceReply_DiskUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceReply_DiskUsage.Merge(dst, src)
}
func (m *CheckDiskSpaceReply_DiskUsage) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceReply_DiskUsage.Size(m)
}
func (m *CheckDiskSpaceReply_DiskUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceReply_DiskUsage.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceReply_DiskUsage proto.InternalMessageInfo

func (m *CheckDiskSpaceReply_DiskUsage) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *CheckDiskSpaceReply_DiskUsage) GetRequired() uint64 {
	if m != nil {
		return m.Required
	}
	return 0
}

type PrepareInitClusterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterRequest) Reset()         { *m = PrepareInitClusterRequest{} }
func (m *PrepareInitClusterRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterRequest) ProtoMessage()    {}
func (*PrepareInitClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{12}
}
func (m *PrepareInitClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterRequest.Unmarshal(m, b)
}
func (m *PrepareInitClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterRequest.Marshal(b, m, deterministic)
}
func (dst *PrepareInitClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterRequest.Merge(dst, src)
}
func (m *PrepareInitClusterRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterRequest.Size(m)
}
func (m *PrepareInitClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterRequest proto.InternalMessageInfo

type PrepareInitClusterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterReply) Reset()         { *m = PrepareInitClusterReply{} }
func (m *PrepareInitClusterReply) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterReply) ProtoMessage()    {}
func (*PrepareInitClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{13}
}
func (m *PrepareInitClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterReply.Unmarshal(m, b)
}
func (m *PrepareInitClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterReply.Marshal(b, m, deterministic)
}
func (dst *PrepareInitClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterReply.Merge(dst, src)
}
func (m *PrepareInitClusterReply) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterReply.Size(m)
}
func (m *PrepareInitClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterReply proto.InternalMessageInfo

type Chunk struct {
	Buffer               []byte     `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Type                 Chunk_Type `protobuf:"varint,2,opt,name=type,enum=idl.Chunk_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{14}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (dst *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(dst, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *Chunk) GetType() Chunk_Type {
	if m != nil {
		return m.Type
	}
	return Chunk_UNKNOWN
}

type Message struct {
	// Types that are valid to be assigned to Contents:
	//	*Message_Chunk
	//	*Message_Status
	Contents             isMessage_Contents `protobuf_oneof:"contents"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{15}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Contents interface {
	isMessage_Contents()
}

type Message_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,1,opt,name=chunk,oneof"`
}
type Message_Status struct {
	Status *UpgradeStepStatus `protobuf:"bytes,2,opt,name=status,oneof"`
}

func (*Message_Chunk) isMessage_Contents()  {}
func (*Message_Status) isMessage_Contents() {}

func (m *Message) GetContents() isMessage_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Message) GetChunk() *Chunk {
	if x, ok := m.GetContents().(*Message_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *Message) GetStatus() *UpgradeStepStatus {
	if x, ok := m.GetContents().(*Message_Status); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Chunk)(nil),
		(*Message_Status)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// contents
	switch x := m.Contents.(type) {
	case *Message_Chunk:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Chunk); err != nil {
			return err
		}
	case *Message_Status:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Status); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Contents has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 1: // contents.chunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Chunk)
		err := b.DecodeMessage(msg)
		m.Contents = &Message_Chunk{msg}
		return true, err
	case 2: // contents.status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpgradeStepStatus)
		err := b.DecodeMessage(msg)
		m.Contents = &Message_Status{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// contents
	switch x := m.Contents.(type) {
	case *Message_Chunk:
		s := proto.Size(x.Chunk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Status:
		s := proto.Size(x.Status)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{16}
}
func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(dst, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetConfigRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetConfigReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigReply) Reset()         { *m = SetConfigReply{} }
func (m *SetConfigReply) String() string { return proto.CompactTextString(m) }
func (*SetConfigReply) ProtoMessage()    {}
func (*SetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{17}
}
func (m *SetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigReply.Unmarshal(m, b)
}
func (m *SetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigReply.Marshal(b, m, deterministic)
}
func (dst *SetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigReply.Merge(dst, src)
}
func (m *SetConfigReply) XXX_Size() int {
	return xxx_messageInfo_SetConfigReply.Size(m)
}
func (m *SetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigReply proto.InternalMessageInfo

type GetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{18}
}
func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(dst, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetConfigReply struct {
	Value                string   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigReply) Reset()         { *m = GetConfigReply{} }
func (m *GetConfigReply) String() string { return proto.CompactTextString(m) }
func (*GetConfigReply) ProtoMessage()    {}
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_70b0961962f0708b, []int{19}
}
func (m *GetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReply.Unmarshal(m, b)
}
func (m *GetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReply.Marshal(b, m, deterministic)
}
func (dst *GetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReply.Merge(dst, src)
}
func (m *GetConfigReply) XXX_Size() int {
	return xxx_messageInfo_GetConfigReply.Size(m)
}
func (m *GetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReply proto.InternalMessageInfo

func (m *GetConfigReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*InitializeRequest)(nil), "idl.InitializeRequest")
	proto.RegisterType((*ExecuteRequest)(nil), "idl.ExecuteRequest")
	proto.RegisterType((*FinalizeRequest)(nil), "idl.FinalizeRequest")
	proto.RegisterType((*RestartAgentsRequest)(nil), "idl.RestartAgentsRequest")
	proto.RegisterType((*RestartAgentsReply)(nil), "idl.RestartAgentsReply")
	proto.RegisterType((*StopServicesRequest)(nil), "idl.StopServicesRequest")
	proto.RegisterType((*StopServicesReply)(nil), "idl.StopServicesReply")
	proto.RegisterType((*UpgradeStepStatus)(nil), "idl.UpgradeStepStatus")
	proto.RegisterType((*CheckVersionRequest)(nil), "idl.CheckVersionRequest")
	proto.RegisterType((*CheckVersionReply)(nil), "idl.CheckVersionReply")
	proto.RegisterType((*CheckDiskSpaceRequest)(nil), "idl.CheckDiskSpaceRequest")
	proto.RegisterType((*CheckDiskSpaceReply)(nil), "idl.CheckDiskSpaceReply")
	proto.RegisterMapType((map[string]*CheckDiskSpaceReply_DiskUsage)(nil), "idl.CheckDiskSpaceReply.FailedEntry")
	proto.RegisterType((*CheckDiskSpaceReply_DiskUsage)(nil), "idl.CheckDiskSpaceReply.DiskUsage")
	proto.RegisterType((*PrepareInitClusterRequest)(nil), "idl.PrepareInitClusterRequest")
	proto.RegisterType((*PrepareInitClusterReply)(nil), "idl.PrepareInitClusterReply")
	proto.RegisterType((*Chunk)(nil), "idl.Chunk")
	proto.RegisterType((*Message)(nil), "idl.Message")
	proto.RegisterType((*SetConfigRequest)(nil), "idl.SetConfigRequest")
	proto.RegisterType((*SetConfigReply)(nil), "idl.SetConfigReply")
	proto.RegisterType((*GetConfigRequest)(nil), "idl.GetConfigRequest")
	proto.RegisterType((*GetConfigReply)(nil), "idl.GetConfigReply")
	proto.RegisterEnum("idl.UpgradeSteps", UpgradeSteps_name, UpgradeSteps_value)
	proto.RegisterEnum("idl.StepStatus", StepStatus_name, StepStatus_value)
	proto.RegisterEnum("idl.Chunk_Type", Chunk_Type_name, Chunk_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CliToHub service

type CliToHubClient interface {
	CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionReply, error)
	CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error)
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error)
	StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error)
}

type cliToHubClient struct {
	cc *grpc.ClientConn
}

func NewCliToHubClient(cc *grpc.ClientConn) CliToHubClient {
	return &cliToHubClient{cc}
}

func (c *cliToHubClient) CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionReply, error) {
	out := new(CheckVersionReply)
	err := grpc.Invoke(ctx, "/idl.CliToHub/CheckVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error) {
	out := new(CheckDiskSpaceReply)
	err := grpc.Invoke(ctx, "/idl.CliToHub/CheckDiskSpace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CliToHub_serviceDesc.Streams[0], c.cc, "/idl.CliToHub/Initialize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubInitializeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_InitializeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubInitializeClient struct {
	grpc.ClientStream
}

func (x *cliToHubInitializeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CliToHub_serviceDesc.Streams[1], c.cc, "/idl.CliToHub/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_ExecuteClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubExecuteClient struct {
	grpc.ClientStream
}

func (x *cliToHubExecuteClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CliToHub_serviceDesc.Streams[2], c.cc, "/idl.CliToHub/Finalize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubFinalizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_FinalizeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubFinalizeClient struct {
	grpc.ClientStream
}

func (x *cliToHubFinalizeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error) {
	out := new(SetConfigReply)
	err := grpc.Invoke(ctx, "/idl.CliToHub/SetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	out := new(GetConfigReply)
	err := grpc.Invoke(ctx, "/idl.CliToHub/GetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error) {
	out := new(RestartAgentsReply)
	err := grpc.Invoke(ctx, "/idl.CliToHub/RestartAgents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error) {
	out := new(StopServicesReply)
	err := grpc.Invoke(ctx, "/idl.CliToHub/StopServices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CliToHub service

type CliToHubServer interface {
	CheckVersion(context.Context, *CheckVersionRequest) (*CheckVersionReply, error)
	CheckDiskSpace(context.Context, *CheckDiskSpaceRequest) (*CheckDiskSpaceReply, error)
	Initialize(*InitializeRequest, CliToHub_InitializeServer) error
	Execute(*ExecuteRequest, CliToHub_ExecuteServer) error
	Finalize(*FinalizeRequest, CliToHub_FinalizeServer) error
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigReply, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	RestartAgents(context.Context, *RestartAgentsRequest) (*RestartAgentsReply, error)
	StopServices(context.Context, *StopServicesRequest) (*StopServicesReply, error)
}

func RegisterCliToHubServer(s *grpc.Server, srv CliToHubServer) {
	s.RegisterService(&_CliToHub_serviceDesc, srv)
}

func _CliToHub_CheckVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckVersion(ctx, req.(*CheckVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDiskSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckDiskSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckDiskSpace(ctx, req.(*CheckDiskSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_Initialize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Initialize(m, &cliToHubInitializeServer{stream})
}

type CliToHub_InitializeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubInitializeServer struct {
	grpc.ServerStream
}

func (x *cliToHubInitializeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Execute(m, &cliToHubExecuteServer{stream})
}

type CliToHub_ExecuteServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubExecuteServer struct {
	grpc.ServerStream
}

func (x *cliToHubExecuteServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Finalize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FinalizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Finalize(m, &cliToHubFinalizeServer{stream})
}

type CliToHub_FinalizeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubFinalizeServer struct {
	grpc.ServerStream
}

func (x *cliToHubFinalizeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_RestartAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).RestartAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/RestartAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).RestartAgents(ctx, req.(*RestartAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_StopServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).StopServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/StopServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).StopServices(ctx, req.(*StopServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CliToHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.CliToHub",
	HandlerType: (*CliToHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckVersion",
			Handler:    _CliToHub_CheckVersion_Handler,
		},
		{
			MethodName: "CheckDiskSpace",
			Handler:    _CliToHub_CheckDiskSpace_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _CliToHub_SetConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _CliToHub_GetConfig_Handler,
		},
		{
			MethodName: "RestartAgents",
			Handler:    _CliToHub_RestartAgents_Handler,
		},
		{
			MethodName: "StopServices",
			Handler:    _CliToHub_StopServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Initialize",
			Handler:       _CliToHub_Initialize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _CliToHub_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Finalize",
			Handler:       _CliToHub_Finalize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cli_to_hub.proto",
}

func init() { proto.RegisterFile("cli_to_hub.proto", fileDescriptor_cli_to_hub_70b0961962f0708b) }

var fileDescriptor_cli_to_hub_70b0961962f0708b = []byte{
	// 1016 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x6d, 0x6f, 0xe2, 0xc6,
	0x13, 0xe7, 0xf9, 0x61, 0xe0, 0x88, 0x59, 0xf2, 0x40, 0xb8, 0xbf, 0xfe, 0x8a, 0xdc, 0xf6, 0x1a,
	0x5d, 0xd5, 0x28, 0xa2, 0x55, 0x75, 0x57, 0xdd, 0x1b, 0x62, 0x36, 0x80, 0x9a, 0x00, 0x5a, 0xdb,
	0xad, 0xfa, 0xa2, 0x42, 0x0e, 0x6c, 0x92, 0x55, 0x7c, 0xb6, 0x63, 0x2f, 0x69, 0xe9, 0x27, 0xe9,
	0x37, 0xe9, 0x67, 0xeb, 0xbb, 0x6a, 0xd7, 0x36, 0xd8, 0x9c, 0x4f, 0xea, 0x3b, 0xcf, 0xfc, 0xe6,
	0x37, 0x3b, 0xfe, 0x79, 0x66, 0xc7, 0xa0, 0x2c, 0x6d, 0xb6, 0xe0, 0xee, 0xe2, 0x71, 0x7d, 0x77,
	0xe1, 0xf9, 0x2e, 0x77, 0x51, 0x91, 0xad, 0x6c, 0x95, 0x41, 0x7b, 0xe2, 0x30, 0xce, 0x2c, 0x9b,
	0xfd, 0x49, 0x09, 0x7d, 0x5e, 0xd3, 0x80, 0xa3, 0xff, 0x41, 0xdd, 0xb5, 0x57, 0x57, 0xcc, 0x19,
	0x32, 0xbf, 0x9b, 0x3f, 0xcb, 0x9f, 0xd7, 0xc9, 0xce, 0x21, 0x50, 0x87, 0xfe, 0x1e, 0xa1, 0x85,
	0x10, 0xdd, 0x3a, 0x50, 0x17, 0xaa, 0xae, 0xbd, 0x9a, 0xbb, 0x3e, 0xef, 0x16, 0xcf, 0xf2, 0xe7,
	0x65, 0x12, 0x9b, 0xea, 0x1b, 0x68, 0xe1, 0x3f, 0xe8, 0x72, 0xcd, 0xb7, 0xe7, 0x1c, 0x42, 0xd9,
	0x73, 0x7d, 0x1e, 0x74, 0xf3, 0x67, 0xc5, 0xf3, 0x57, 0x24, 0x34, 0xd4, 0x36, 0x1c, 0x5c, 0x33,
	0x27, 0x59, 0x90, 0x7a, 0x0c, 0x87, 0x84, 0x06, 0xdc, 0xf2, 0xf9, 0xe0, 0x81, 0x3a, 0x3c, 0x88,
	0xfd, 0xdf, 0x03, 0xda, 0xf3, 0x7b, 0xf6, 0x06, 0xfd, 0x1f, 0xc0, 0x12, 0xe6, 0xd8, 0x0d, 0xa2,
	0xdc, 0x75, 0x92, 0xf0, 0xa8, 0x47, 0xd0, 0xd1, 0xb9, 0xeb, 0xe9, 0xd4, 0x7f, 0x61, 0x4b, 0xba,
	0x4d, 0xd6, 0x81, 0x76, 0xda, 0xed, 0xd9, 0x1b, 0x75, 0x09, 0x6d, 0xd3, 0x7b, 0xf0, 0xad, 0x15,
	0xd5, 0x39, 0xf5, 0x74, 0x6e, 0xf1, 0x75, 0x80, 0xbe, 0x82, 0x52, 0xc0, 0xa9, 0x27, 0xa5, 0x69,
	0xf5, 0xdb, 0x17, 0x6c, 0x65, 0x5f, 0x24, 0xa2, 0x02, 0x22, 0x61, 0xf4, 0x35, 0x54, 0x02, 0x49,
	0x90, 0x2a, 0xb5, 0xfa, 0x07, 0x32, 0x70, 0x97, 0x87, 0x44, 0xb0, 0x28, 0x48, 0x7b, 0xa4, 0xcb,
	0xa7, 0x9f, 0xa9, 0x1f, 0x30, 0xd7, 0x89, 0x0b, 0xc2, 0xd0, 0x4e, 0xbb, 0xc5, 0xcb, 0x5d, 0x42,
	0x67, 0x12, 0x44, 0x1e, 0xcd, 0xfd, 0xe8, 0x59, 0x9c, 0xdd, 0xd9, 0x54, 0x96, 0x52, 0x23, 0x59,
	0x90, 0xfa, 0x2d, 0x1c, 0xc9, 0x34, 0x43, 0x16, 0x3c, 0xe9, 0x9e, 0xb5, 0x4c, 0xca, 0xef, 0x5b,
	0x9c, 0xb9, 0x92, 0x5c, 0x20, 0xa1, 0xa1, 0xfe, 0x93, 0x8f, 0xaa, 0x49, 0xc4, 0x8b, 0x83, 0x3f,
	0x40, 0xe5, 0xde, 0x62, 0x36, 0x5d, 0x49, 0x45, 0x1b, 0xfd, 0x2f, 0xe5, 0xdb, 0x64, 0x44, 0x5e,
	0x5c, 0xcb, 0x30, 0xec, 0x70, 0x7f, 0x43, 0x22, 0x4e, 0x0f, 0x43, 0x5d, 0x44, 0x99, 0x81, 0xf5,
	0x40, 0x45, 0x07, 0x59, 0x2f, 0x16, 0xb3, 0xad, 0xb8, 0xf2, 0x12, 0xd9, 0x39, 0x50, 0x0f, 0x6a,
	0x3e, 0x7d, 0x5e, 0x33, 0x9f, 0xae, 0xa4, 0x70, 0x25, 0xb2, 0xb5, 0x7b, 0xbf, 0x41, 0x23, 0x91,
	0x1d, 0x29, 0x50, 0x7c, 0xa2, 0x9b, 0xa8, 0x45, 0xc5, 0x23, 0x7a, 0x07, 0xe5, 0x17, 0xcb, 0x5e,
	0x53, 0xc9, 0x6c, 0xf4, 0xd5, 0xcf, 0x16, 0xb9, 0xad, 0x86, 0x84, 0x84, 0x1f, 0x0b, 0xef, 0xf2,
	0xea, 0x6b, 0x38, 0x9d, 0xfb, 0xd4, 0xb3, 0x7c, 0x2a, 0x86, 0x42, 0xb3, 0xd7, 0x01, 0xa7, 0x7e,
	0xfc, 0x39, 0x4e, 0xe1, 0x24, 0x0b, 0x14, 0x5d, 0xf2, 0x0c, 0x65, 0xed, 0x71, 0xed, 0x3c, 0xa1,
	0x63, 0xa8, 0xdc, 0xad, 0xef, 0xef, 0x69, 0x38, 0x36, 0x4d, 0x12, 0x59, 0xe8, 0x0b, 0x28, 0xf1,
	0x8d, 0x47, 0x53, 0x8d, 0x20, 0x19, 0x17, 0xc6, 0xc6, 0xa3, 0x44, 0x82, 0xea, 0x37, 0x50, 0x12,
	0x16, 0x6a, 0x40, 0xd5, 0x9c, 0xfe, 0x34, 0x9d, 0xfd, 0x32, 0x55, 0x72, 0x08, 0xa0, 0xa2, 0x1b,
	0xc3, 0x99, 0x69, 0x28, 0xf9, 0xe8, 0x19, 0x13, 0xa2, 0x14, 0xd4, 0x27, 0xa8, 0xde, 0xd2, 0x40,
	0xca, 0xa9, 0x42, 0x79, 0x29, 0x72, 0xc9, 0x33, 0x1b, 0x7d, 0xd8, 0x65, 0x1f, 0xe7, 0x48, 0x08,
	0xa1, 0xcb, 0x54, 0x2f, 0x36, 0xfa, 0xc7, 0xfb, 0x4d, 0x1b, 0xb6, 0xe4, 0x38, 0x17, 0x37, 0xe5,
	0x15, 0x40, 0x6d, 0xe9, 0x3a, 0x5c, 0x8c, 0x95, 0xfa, 0x01, 0x14, 0x9d, 0x72, 0xcd, 0x75, 0xee,
	0xd9, 0x43, 0xdc, 0x3d, 0x08, 0x4a, 0x8e, 0xf5, 0x91, 0x46, 0xe2, 0xcb, 0x67, 0xd1, 0x51, 0x3b,
	0xf5, 0xeb, 0x91, 0xb2, 0xaa, 0x02, 0xad, 0x04, 0x5b, 0xe8, 0xf5, 0x06, 0x94, 0xd1, 0x7f, 0xc8,
	0x27, 0xae, 0x8c, 0x51, 0x8a, 0xb9, 0x3b, 0x21, 0x9f, 0x38, 0xe1, 0xed, 0x5f, 0x05, 0x68, 0x26,
	0x07, 0x10, 0x29, 0xd0, 0x8c, 0x24, 0x5c, 0xe8, 0x06, 0x9e, 0x87, 0x3a, 0x6a, 0xb3, 0xe9, 0xf5,
	0x64, 0xa4, 0xe4, 0x05, 0xaa, 0x1b, 0x03, 0x62, 0x2c, 0x06, 0x23, 0x3c, 0x35, 0x74, 0xa5, 0x80,
	0xba, 0x70, 0xa8, 0x11, 0x3c, 0x30, 0xf0, 0xc2, 0x18, 0x90, 0x11, 0x36, 0x16, 0x51, 0x6c, 0x11,
	0xbd, 0x86, 0x13, 0x7d, 0x6c, 0x1a, 0x43, 0x99, 0x6a, 0x66, 0x12, 0x0d, 0x2f, 0xb4, 0x1b, 0x53,
	0x37, 0x30, 0x51, 0x4a, 0xe8, 0x04, 0x3a, 0x93, 0xe9, 0xc4, 0xd8, 0x92, 0x22, 0xa0, 0x9c, 0x62,
	0xed, 0x81, 0x15, 0x84, 0xa0, 0x65, 0xce, 0x47, 0x64, 0x30, 0xc4, 0x8b, 0xdb, 0x81, 0xf4, 0x55,
	0xd1, 0x01, 0x34, 0xb4, 0xd9, 0xfc, 0xd7, 0xd8, 0x51, 0x43, 0x47, 0xd0, 0x8e, 0x83, 0xe6, 0x64,
	0x72, 0x3b, 0x20, 0x13, 0xac, 0x2b, 0x75, 0x51, 0x68, 0x58, 0xfa, 0x5e, 0x56, 0x10, 0x04, 0x82,
	0xc3, 0xb2, 0x4d, 0x82, 0x17, 0xf3, 0x19, 0x31, 0x74, 0xa5, 0xf1, 0xd6, 0x00, 0x48, 0xdc, 0x5c,
	0xe2, 0xe8, 0xad, 0x2e, 0x03, 0xc3, 0xd4, 0x95, 0x9c, 0x68, 0xb7, 0x39, 0x9e, 0x0e, 0x27, 0x53,
	0x21, 0x4d, 0x03, 0xaa, 0xc4, 0x9c, 0x4e, 0x85, 0x51, 0x40, 0x4d, 0xa8, 0x69, 0xb3, 0xdb, 0xf9,
	0x0d, 0x36, 0xb0, 0x52, 0x14, 0x0a, 0x5e, 0x0f, 0x26, 0x37, 0x78, 0xa8, 0x94, 0xfa, 0x7f, 0x97,
	0xa0, 0xa6, 0xd9, 0xcc, 0x70, 0xc7, 0xeb, 0x3b, 0x74, 0x05, 0xcd, 0xe4, 0x3d, 0x85, 0xba, 0xbb,
	0xa1, 0x4b, 0xdf, 0x68, 0xbd, 0xe3, 0x0c, 0x44, 0xf4, 0x43, 0x0e, 0x8d, 0xa1, 0x95, 0x9e, 0x52,
	0xd4, 0xcb, 0x1c, 0xdd, 0x30, 0x4f, 0xf7, 0x73, 0x63, 0xad, 0xe6, 0xd0, 0x0f, 0x00, 0xbb, 0x8d,
	0x86, 0xc2, 0x13, 0x3f, 0x59, 0x71, 0xbd, 0xa6, 0xf4, 0x47, 0x13, 0xa4, 0xe6, 0x2e, 0xf3, 0xe8,
	0x12, 0xaa, 0xd1, 0x7a, 0x42, 0x1d, 0x09, 0xa6, 0x97, 0x55, 0x06, 0xa3, 0x0f, 0xb5, 0x78, 0x51,
	0xa1, 0x43, 0x89, 0xee, 0xed, 0xad, 0x0c, 0xce, 0x7b, 0xa8, 0x6f, 0x67, 0x01, 0x1d, 0x85, 0x0b,
	0x61, 0x6f, 0x12, 0x7a, 0x9d, 0x7d, 0x77, 0xf8, 0x62, 0xef, 0xa1, 0x3e, 0xda, 0xa3, 0x8e, 0xb2,
	0xa9, 0xa3, 0x7d, 0x2a, 0x86, 0x57, 0xa9, 0x3d, 0x89, 0x4e, 0x65, 0x5c, 0xd6, 0x4e, 0xed, 0x9d,
	0x64, 0x41, 0x61, 0x9a, 0x2b, 0x68, 0x26, 0x37, 0x64, 0xf4, 0xa1, 0x33, 0x76, 0x69, 0xf4, 0xa1,
	0x3f, 0x5d, 0xa7, 0xb9, 0xbb, 0x8a, 0xfc, 0xf9, 0xf8, 0xee, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x52, 0xe0, 0x54, 0x0a, 0x90, 0x08, 0x00, 0x00,
}
