// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cli_to_hub.proto

package idl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpgradeSteps int32

const (
	UpgradeSteps_UNKNOWN_STEP           UpgradeSteps = 0
	UpgradeSteps_CONFIG                 UpgradeSteps = 1
	UpgradeSteps_SEGINSTALL             UpgradeSteps = 2
	UpgradeSteps_START_AGENTS           UpgradeSteps = 3
	UpgradeSteps_INIT_CLUSTER           UpgradeSteps = 4
	UpgradeSteps_SHUTDOWN_CLUSTERS      UpgradeSteps = 5
	UpgradeSteps_CONVERT_MASTER         UpgradeSteps = 6
	UpgradeSteps_SHARE_OIDS             UpgradeSteps = 7
	UpgradeSteps_CONVERT_PRIMARIES      UpgradeSteps = 8
	UpgradeSteps_VALIDATE_START_CLUSTER UpgradeSteps = 9
	UpgradeSteps_RECONFIGURE_PORTS      UpgradeSteps = 10
)

var UpgradeSteps_name = map[int32]string{
	0:  "UNKNOWN_STEP",
	1:  "CONFIG",
	2:  "SEGINSTALL",
	3:  "START_AGENTS",
	4:  "INIT_CLUSTER",
	5:  "SHUTDOWN_CLUSTERS",
	6:  "CONVERT_MASTER",
	7:  "SHARE_OIDS",
	8:  "CONVERT_PRIMARIES",
	9:  "VALIDATE_START_CLUSTER",
	10: "RECONFIGURE_PORTS",
}
var UpgradeSteps_value = map[string]int32{
	"UNKNOWN_STEP":           0,
	"CONFIG":                 1,
	"SEGINSTALL":             2,
	"START_AGENTS":           3,
	"INIT_CLUSTER":           4,
	"SHUTDOWN_CLUSTERS":      5,
	"CONVERT_MASTER":         6,
	"SHARE_OIDS":             7,
	"CONVERT_PRIMARIES":      8,
	"VALIDATE_START_CLUSTER": 9,
	"RECONFIGURE_PORTS":      10,
}

func (x UpgradeSteps) String() string {
	return proto.EnumName(UpgradeSteps_name, int32(x))
}
func (UpgradeSteps) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{0}
}

type StepStatus int32

const (
	StepStatus_UNKNOWN_STATUS StepStatus = 0
	StepStatus_PENDING        StepStatus = 1
	StepStatus_RUNNING        StepStatus = 2
	StepStatus_COMPLETE       StepStatus = 3
	StepStatus_FAILED         StepStatus = 4
)

var StepStatus_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "PENDING",
	2: "RUNNING",
	3: "COMPLETE",
	4: "FAILED",
}
var StepStatus_value = map[string]int32{
	"UNKNOWN_STATUS": 0,
	"PENDING":        1,
	"RUNNING":        2,
	"COMPLETE":       3,
	"FAILED":         4,
}

func (x StepStatus) String() string {
	return proto.EnumName(StepStatus_name, int32(x))
}
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{1}
}

type WhichCluster int32

const (
	WhichCluster_UNKNOWN WhichCluster = 0
	WhichCluster_SOURCE  WhichCluster = 1
	WhichCluster_TARGET  WhichCluster = 2
)

var WhichCluster_name = map[int32]string{
	0: "UNKNOWN",
	1: "SOURCE",
	2: "TARGET",
}
var WhichCluster_value = map[string]int32{
	"UNKNOWN": 0,
	"SOURCE":  1,
	"TARGET":  2,
}

func (x WhichCluster) String() string {
	return proto.EnumName(WhichCluster_name, int32(x))
}
func (WhichCluster) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{2}
}

type UpgradeReconfigurePortsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeReconfigurePortsRequest) Reset()         { *m = UpgradeReconfigurePortsRequest{} }
func (m *UpgradeReconfigurePortsRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeReconfigurePortsRequest) ProtoMessage()    {}
func (*UpgradeReconfigurePortsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{0}
}
func (m *UpgradeReconfigurePortsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeReconfigurePortsRequest.Unmarshal(m, b)
}
func (m *UpgradeReconfigurePortsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeReconfigurePortsRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradeReconfigurePortsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeReconfigurePortsRequest.Merge(dst, src)
}
func (m *UpgradeReconfigurePortsRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeReconfigurePortsRequest.Size(m)
}
func (m *UpgradeReconfigurePortsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeReconfigurePortsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeReconfigurePortsRequest proto.InternalMessageInfo

type UpgradeReconfigurePortsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeReconfigurePortsReply) Reset()         { *m = UpgradeReconfigurePortsReply{} }
func (m *UpgradeReconfigurePortsReply) String() string { return proto.CompactTextString(m) }
func (*UpgradeReconfigurePortsReply) ProtoMessage()    {}
func (*UpgradeReconfigurePortsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{1}
}
func (m *UpgradeReconfigurePortsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeReconfigurePortsReply.Unmarshal(m, b)
}
func (m *UpgradeReconfigurePortsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeReconfigurePortsReply.Marshal(b, m, deterministic)
}
func (dst *UpgradeReconfigurePortsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeReconfigurePortsReply.Merge(dst, src)
}
func (m *UpgradeReconfigurePortsReply) XXX_Size() int {
	return xxx_messageInfo_UpgradeReconfigurePortsReply.Size(m)
}
func (m *UpgradeReconfigurePortsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeReconfigurePortsReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeReconfigurePortsReply proto.InternalMessageInfo

type UpgradeConvertPrimariesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeConvertPrimariesRequest) Reset()         { *m = UpgradeConvertPrimariesRequest{} }
func (m *UpgradeConvertPrimariesRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeConvertPrimariesRequest) ProtoMessage()    {}
func (*UpgradeConvertPrimariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{2}
}
func (m *UpgradeConvertPrimariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeConvertPrimariesRequest.Unmarshal(m, b)
}
func (m *UpgradeConvertPrimariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeConvertPrimariesRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradeConvertPrimariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeConvertPrimariesRequest.Merge(dst, src)
}
func (m *UpgradeConvertPrimariesRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeConvertPrimariesRequest.Size(m)
}
func (m *UpgradeConvertPrimariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeConvertPrimariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeConvertPrimariesRequest proto.InternalMessageInfo

type UpgradeConvertPrimariesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeConvertPrimariesReply) Reset()         { *m = UpgradeConvertPrimariesReply{} }
func (m *UpgradeConvertPrimariesReply) String() string { return proto.CompactTextString(m) }
func (*UpgradeConvertPrimariesReply) ProtoMessage()    {}
func (*UpgradeConvertPrimariesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{3}
}
func (m *UpgradeConvertPrimariesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeConvertPrimariesReply.Unmarshal(m, b)
}
func (m *UpgradeConvertPrimariesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeConvertPrimariesReply.Marshal(b, m, deterministic)
}
func (dst *UpgradeConvertPrimariesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeConvertPrimariesReply.Merge(dst, src)
}
func (m *UpgradeConvertPrimariesReply) XXX_Size() int {
	return xxx_messageInfo_UpgradeConvertPrimariesReply.Size(m)
}
func (m *UpgradeConvertPrimariesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeConvertPrimariesReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeConvertPrimariesReply proto.InternalMessageInfo

type UpgradeShareOidsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeShareOidsRequest) Reset()         { *m = UpgradeShareOidsRequest{} }
func (m *UpgradeShareOidsRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeShareOidsRequest) ProtoMessage()    {}
func (*UpgradeShareOidsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{4}
}
func (m *UpgradeShareOidsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeShareOidsRequest.Unmarshal(m, b)
}
func (m *UpgradeShareOidsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeShareOidsRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradeShareOidsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeShareOidsRequest.Merge(dst, src)
}
func (m *UpgradeShareOidsRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeShareOidsRequest.Size(m)
}
func (m *UpgradeShareOidsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeShareOidsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeShareOidsRequest proto.InternalMessageInfo

type UpgradeShareOidsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeShareOidsReply) Reset()         { *m = UpgradeShareOidsReply{} }
func (m *UpgradeShareOidsReply) String() string { return proto.CompactTextString(m) }
func (*UpgradeShareOidsReply) ProtoMessage()    {}
func (*UpgradeShareOidsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{5}
}
func (m *UpgradeShareOidsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeShareOidsReply.Unmarshal(m, b)
}
func (m *UpgradeShareOidsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeShareOidsReply.Marshal(b, m, deterministic)
}
func (dst *UpgradeShareOidsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeShareOidsReply.Merge(dst, src)
}
func (m *UpgradeShareOidsReply) XXX_Size() int {
	return xxx_messageInfo_UpgradeShareOidsReply.Size(m)
}
func (m *UpgradeShareOidsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeShareOidsReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeShareOidsReply proto.InternalMessageInfo

type UpgradeValidateStartClusterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeValidateStartClusterRequest) Reset()         { *m = UpgradeValidateStartClusterRequest{} }
func (m *UpgradeValidateStartClusterRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeValidateStartClusterRequest) ProtoMessage()    {}
func (*UpgradeValidateStartClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{6}
}
func (m *UpgradeValidateStartClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeValidateStartClusterRequest.Unmarshal(m, b)
}
func (m *UpgradeValidateStartClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeValidateStartClusterRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradeValidateStartClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeValidateStartClusterRequest.Merge(dst, src)
}
func (m *UpgradeValidateStartClusterRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeValidateStartClusterRequest.Size(m)
}
func (m *UpgradeValidateStartClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeValidateStartClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeValidateStartClusterRequest proto.InternalMessageInfo

type UpgradeValidateStartClusterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeValidateStartClusterReply) Reset()         { *m = UpgradeValidateStartClusterReply{} }
func (m *UpgradeValidateStartClusterReply) String() string { return proto.CompactTextString(m) }
func (*UpgradeValidateStartClusterReply) ProtoMessage()    {}
func (*UpgradeValidateStartClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{7}
}
func (m *UpgradeValidateStartClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeValidateStartClusterReply.Unmarshal(m, b)
}
func (m *UpgradeValidateStartClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeValidateStartClusterReply.Marshal(b, m, deterministic)
}
func (dst *UpgradeValidateStartClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeValidateStartClusterReply.Merge(dst, src)
}
func (m *UpgradeValidateStartClusterReply) XXX_Size() int {
	return xxx_messageInfo_UpgradeValidateStartClusterReply.Size(m)
}
func (m *UpgradeValidateStartClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeValidateStartClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeValidateStartClusterReply proto.InternalMessageInfo

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{8}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{9}
}
func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (dst *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(dst, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

type StatusConversionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusConversionRequest) Reset()         { *m = StatusConversionRequest{} }
func (m *StatusConversionRequest) String() string { return proto.CompactTextString(m) }
func (*StatusConversionRequest) ProtoMessage()    {}
func (*StatusConversionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{10}
}
func (m *StatusConversionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusConversionRequest.Unmarshal(m, b)
}
func (m *StatusConversionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusConversionRequest.Marshal(b, m, deterministic)
}
func (dst *StatusConversionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusConversionRequest.Merge(dst, src)
}
func (m *StatusConversionRequest) XXX_Size() int {
	return xxx_messageInfo_StatusConversionRequest.Size(m)
}
func (m *StatusConversionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusConversionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusConversionRequest proto.InternalMessageInfo

type PrimaryStatus struct {
	Status               StepStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=idl.StepStatus" json:"Status,omitempty"`
	Dbid                 int32      `protobuf:"varint,2,opt,name=Dbid,proto3" json:"Dbid,omitempty"`
	Content              int32      `protobuf:"varint,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Hostname             string     `protobuf:"bytes,4,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PrimaryStatus) Reset()         { *m = PrimaryStatus{} }
func (m *PrimaryStatus) String() string { return proto.CompactTextString(m) }
func (*PrimaryStatus) ProtoMessage()    {}
func (*PrimaryStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{11}
}
func (m *PrimaryStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryStatus.Unmarshal(m, b)
}
func (m *PrimaryStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryStatus.Marshal(b, m, deterministic)
}
func (dst *PrimaryStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryStatus.Merge(dst, src)
}
func (m *PrimaryStatus) XXX_Size() int {
	return xxx_messageInfo_PrimaryStatus.Size(m)
}
func (m *PrimaryStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryStatus proto.InternalMessageInfo

func (m *PrimaryStatus) GetStatus() StepStatus {
	if m != nil {
		return m.Status
	}
	return StepStatus_UNKNOWN_STATUS
}

func (m *PrimaryStatus) GetDbid() int32 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *PrimaryStatus) GetContent() int32 {
	if m != nil {
		return m.Content
	}
	return 0
}

func (m *PrimaryStatus) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type StatusConversionReply struct {
	ConversionStatuses   []*PrimaryStatus `protobuf:"bytes,1,rep,name=conversionStatuses,proto3" json:"conversionStatuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StatusConversionReply) Reset()         { *m = StatusConversionReply{} }
func (m *StatusConversionReply) String() string { return proto.CompactTextString(m) }
func (*StatusConversionReply) ProtoMessage()    {}
func (*StatusConversionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{12}
}
func (m *StatusConversionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusConversionReply.Unmarshal(m, b)
}
func (m *StatusConversionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusConversionReply.Marshal(b, m, deterministic)
}
func (dst *StatusConversionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusConversionReply.Merge(dst, src)
}
func (m *StatusConversionReply) XXX_Size() int {
	return xxx_messageInfo_StatusConversionReply.Size(m)
}
func (m *StatusConversionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusConversionReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusConversionReply proto.InternalMessageInfo

func (m *StatusConversionReply) GetConversionStatuses() []*PrimaryStatus {
	if m != nil {
		return m.ConversionStatuses
	}
	return nil
}

type StatusUpgradeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusUpgradeRequest) Reset()         { *m = StatusUpgradeRequest{} }
func (m *StatusUpgradeRequest) String() string { return proto.CompactTextString(m) }
func (*StatusUpgradeRequest) ProtoMessage()    {}
func (*StatusUpgradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{13}
}
func (m *StatusUpgradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusUpgradeRequest.Unmarshal(m, b)
}
func (m *StatusUpgradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusUpgradeRequest.Marshal(b, m, deterministic)
}
func (dst *StatusUpgradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusUpgradeRequest.Merge(dst, src)
}
func (m *StatusUpgradeRequest) XXX_Size() int {
	return xxx_messageInfo_StatusUpgradeRequest.Size(m)
}
func (m *StatusUpgradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusUpgradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusUpgradeRequest proto.InternalMessageInfo

type StatusUpgradeReply struct {
	ListOfUpgradeStepStatuses []*UpgradeStepStatus `protobuf:"bytes,1,rep,name=listOfUpgradeStepStatuses,proto3" json:"listOfUpgradeStepStatuses,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}             `json:"-"`
	XXX_unrecognized          []byte               `json:"-"`
	XXX_sizecache             int32                `json:"-"`
}

func (m *StatusUpgradeReply) Reset()         { *m = StatusUpgradeReply{} }
func (m *StatusUpgradeReply) String() string { return proto.CompactTextString(m) }
func (*StatusUpgradeReply) ProtoMessage()    {}
func (*StatusUpgradeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{14}
}
func (m *StatusUpgradeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusUpgradeReply.Unmarshal(m, b)
}
func (m *StatusUpgradeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusUpgradeReply.Marshal(b, m, deterministic)
}
func (dst *StatusUpgradeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusUpgradeReply.Merge(dst, src)
}
func (m *StatusUpgradeReply) XXX_Size() int {
	return xxx_messageInfo_StatusUpgradeReply.Size(m)
}
func (m *StatusUpgradeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusUpgradeReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusUpgradeReply proto.InternalMessageInfo

func (m *StatusUpgradeReply) GetListOfUpgradeStepStatuses() []*UpgradeStepStatus {
	if m != nil {
		return m.ListOfUpgradeStepStatuses
	}
	return nil
}

type UpgradeStepStatus struct {
	Step                 UpgradeSteps `protobuf:"varint,1,opt,name=step,proto3,enum=idl.UpgradeSteps" json:"step,omitempty"`
	Status               StepStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=idl.StepStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpgradeStepStatus) Reset()         { *m = UpgradeStepStatus{} }
func (m *UpgradeStepStatus) String() string { return proto.CompactTextString(m) }
func (*UpgradeStepStatus) ProtoMessage()    {}
func (*UpgradeStepStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{15}
}
func (m *UpgradeStepStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeStepStatus.Unmarshal(m, b)
}
func (m *UpgradeStepStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeStepStatus.Marshal(b, m, deterministic)
}
func (dst *UpgradeStepStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeStepStatus.Merge(dst, src)
}
func (m *UpgradeStepStatus) XXX_Size() int {
	return xxx_messageInfo_UpgradeStepStatus.Size(m)
}
func (m *UpgradeStepStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeStepStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeStepStatus proto.InternalMessageInfo

func (m *UpgradeStepStatus) GetStep() UpgradeSteps {
	if m != nil {
		return m.Step
	}
	return UpgradeSteps_UNKNOWN_STEP
}

func (m *UpgradeStepStatus) GetStatus() StepStatus {
	if m != nil {
		return m.Status
	}
	return StepStatus_UNKNOWN_STATUS
}

type CheckConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckConfigRequest) Reset()         { *m = CheckConfigRequest{} }
func (m *CheckConfigRequest) String() string { return proto.CompactTextString(m) }
func (*CheckConfigRequest) ProtoMessage()    {}
func (*CheckConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{16}
}
func (m *CheckConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConfigRequest.Unmarshal(m, b)
}
func (m *CheckConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConfigRequest.Marshal(b, m, deterministic)
}
func (dst *CheckConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConfigRequest.Merge(dst, src)
}
func (m *CheckConfigRequest) XXX_Size() int {
	return xxx_messageInfo_CheckConfigRequest.Size(m)
}
func (m *CheckConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConfigRequest proto.InternalMessageInfo

// Consider removing the status as errors are/should be put on the error field.
type CheckConfigReply struct {
	ConfigStatus         string   `protobuf:"bytes,1,opt,name=ConfigStatus,proto3" json:"ConfigStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckConfigReply) Reset()         { *m = CheckConfigReply{} }
func (m *CheckConfigReply) String() string { return proto.CompactTextString(m) }
func (*CheckConfigReply) ProtoMessage()    {}
func (*CheckConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{17}
}
func (m *CheckConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConfigReply.Unmarshal(m, b)
}
func (m *CheckConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConfigReply.Marshal(b, m, deterministic)
}
func (dst *CheckConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConfigReply.Merge(dst, src)
}
func (m *CheckConfigReply) XXX_Size() int {
	return xxx_messageInfo_CheckConfigReply.Size(m)
}
func (m *CheckConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConfigReply proto.InternalMessageInfo

func (m *CheckConfigReply) GetConfigStatus() string {
	if m != nil {
		return m.ConfigStatus
	}
	return ""
}

type CheckSeginstallRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSeginstallRequest) Reset()         { *m = CheckSeginstallRequest{} }
func (m *CheckSeginstallRequest) String() string { return proto.CompactTextString(m) }
func (*CheckSeginstallRequest) ProtoMessage()    {}
func (*CheckSeginstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{18}
}
func (m *CheckSeginstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSeginstallRequest.Unmarshal(m, b)
}
func (m *CheckSeginstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSeginstallRequest.Marshal(b, m, deterministic)
}
func (dst *CheckSeginstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSeginstallRequest.Merge(dst, src)
}
func (m *CheckSeginstallRequest) XXX_Size() int {
	return xxx_messageInfo_CheckSeginstallRequest.Size(m)
}
func (m *CheckSeginstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSeginstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSeginstallRequest proto.InternalMessageInfo

type CheckSeginstallReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSeginstallReply) Reset()         { *m = CheckSeginstallReply{} }
func (m *CheckSeginstallReply) String() string { return proto.CompactTextString(m) }
func (*CheckSeginstallReply) ProtoMessage()    {}
func (*CheckSeginstallReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{19}
}
func (m *CheckSeginstallReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSeginstallReply.Unmarshal(m, b)
}
func (m *CheckSeginstallReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSeginstallReply.Marshal(b, m, deterministic)
}
func (dst *CheckSeginstallReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSeginstallReply.Merge(dst, src)
}
func (m *CheckSeginstallReply) XXX_Size() int {
	return xxx_messageInfo_CheckSeginstallReply.Size(m)
}
func (m *CheckSeginstallReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSeginstallReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSeginstallReply proto.InternalMessageInfo

type PrepareStartAgentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareStartAgentsRequest) Reset()         { *m = PrepareStartAgentsRequest{} }
func (m *PrepareStartAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareStartAgentsRequest) ProtoMessage()    {}
func (*PrepareStartAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{20}
}
func (m *PrepareStartAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareStartAgentsRequest.Unmarshal(m, b)
}
func (m *PrepareStartAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareStartAgentsRequest.Marshal(b, m, deterministic)
}
func (dst *PrepareStartAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareStartAgentsRequest.Merge(dst, src)
}
func (m *PrepareStartAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareStartAgentsRequest.Size(m)
}
func (m *PrepareStartAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareStartAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareStartAgentsRequest proto.InternalMessageInfo

type PrepareStartAgentsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareStartAgentsReply) Reset()         { *m = PrepareStartAgentsReply{} }
func (m *PrepareStartAgentsReply) String() string { return proto.CompactTextString(m) }
func (*PrepareStartAgentsReply) ProtoMessage()    {}
func (*PrepareStartAgentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{21}
}
func (m *PrepareStartAgentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareStartAgentsReply.Unmarshal(m, b)
}
func (m *PrepareStartAgentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareStartAgentsReply.Marshal(b, m, deterministic)
}
func (dst *PrepareStartAgentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareStartAgentsReply.Merge(dst, src)
}
func (m *PrepareStartAgentsReply) XXX_Size() int {
	return xxx_messageInfo_PrepareStartAgentsReply.Size(m)
}
func (m *PrepareStartAgentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareStartAgentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareStartAgentsReply proto.InternalMessageInfo

type CountPerDb struct {
	DbName               string   `protobuf:"bytes,1,opt,name=DbName,proto3" json:"DbName,omitempty"`
	AoCount              int32    `protobuf:"varint,2,opt,name=AoCount,proto3" json:"AoCount,omitempty"`
	HeapCount            int32    `protobuf:"varint,3,opt,name=HeapCount,proto3" json:"HeapCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountPerDb) Reset()         { *m = CountPerDb{} }
func (m *CountPerDb) String() string { return proto.CompactTextString(m) }
func (*CountPerDb) ProtoMessage()    {}
func (*CountPerDb) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{22}
}
func (m *CountPerDb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountPerDb.Unmarshal(m, b)
}
func (m *CountPerDb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountPerDb.Marshal(b, m, deterministic)
}
func (dst *CountPerDb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountPerDb.Merge(dst, src)
}
func (m *CountPerDb) XXX_Size() int {
	return xxx_messageInfo_CountPerDb.Size(m)
}
func (m *CountPerDb) XXX_DiscardUnknown() {
	xxx_messageInfo_CountPerDb.DiscardUnknown(m)
}

var xxx_messageInfo_CountPerDb proto.InternalMessageInfo

func (m *CountPerDb) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CountPerDb) GetAoCount() int32 {
	if m != nil {
		return m.AoCount
	}
	return 0
}

func (m *CountPerDb) GetHeapCount() int32 {
	if m != nil {
		return m.HeapCount
	}
	return 0
}

type CheckObjectCountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckObjectCountRequest) Reset()         { *m = CheckObjectCountRequest{} }
func (m *CheckObjectCountRequest) String() string { return proto.CompactTextString(m) }
func (*CheckObjectCountRequest) ProtoMessage()    {}
func (*CheckObjectCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{23}
}
func (m *CheckObjectCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckObjectCountRequest.Unmarshal(m, b)
}
func (m *CheckObjectCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckObjectCountRequest.Marshal(b, m, deterministic)
}
func (dst *CheckObjectCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckObjectCountRequest.Merge(dst, src)
}
func (m *CheckObjectCountRequest) XXX_Size() int {
	return xxx_messageInfo_CheckObjectCountRequest.Size(m)
}
func (m *CheckObjectCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckObjectCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckObjectCountRequest proto.InternalMessageInfo

type CheckObjectCountReply struct {
	ListOfCounts         []*CountPerDb `protobuf:"bytes,1,rep,name=ListOfCounts,proto3" json:"ListOfCounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckObjectCountReply) Reset()         { *m = CheckObjectCountReply{} }
func (m *CheckObjectCountReply) String() string { return proto.CompactTextString(m) }
func (*CheckObjectCountReply) ProtoMessage()    {}
func (*CheckObjectCountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{24}
}
func (m *CheckObjectCountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckObjectCountReply.Unmarshal(m, b)
}
func (m *CheckObjectCountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckObjectCountReply.Marshal(b, m, deterministic)
}
func (dst *CheckObjectCountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckObjectCountReply.Merge(dst, src)
}
func (m *CheckObjectCountReply) XXX_Size() int {
	return xxx_messageInfo_CheckObjectCountReply.Size(m)
}
func (m *CheckObjectCountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckObjectCountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckObjectCountReply proto.InternalMessageInfo

func (m *CheckObjectCountReply) GetListOfCounts() []*CountPerDb {
	if m != nil {
		return m.ListOfCounts
	}
	return nil
}

type CheckVersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionRequest) Reset()         { *m = CheckVersionRequest{} }
func (m *CheckVersionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVersionRequest) ProtoMessage()    {}
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{25}
}
func (m *CheckVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionRequest.Unmarshal(m, b)
}
func (m *CheckVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionRequest.Marshal(b, m, deterministic)
}
func (dst *CheckVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionRequest.Merge(dst, src)
}
func (m *CheckVersionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVersionRequest.Size(m)
}
func (m *CheckVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionRequest proto.InternalMessageInfo

type CheckVersionReply struct {
	IsVersionCompatible  bool     `protobuf:"varint,1,opt,name=IsVersionCompatible,proto3" json:"IsVersionCompatible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionReply) Reset()         { *m = CheckVersionReply{} }
func (m *CheckVersionReply) String() string { return proto.CompactTextString(m) }
func (*CheckVersionReply) ProtoMessage()    {}
func (*CheckVersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{26}
}
func (m *CheckVersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionReply.Unmarshal(m, b)
}
func (m *CheckVersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionReply.Marshal(b, m, deterministic)
}
func (dst *CheckVersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionReply.Merge(dst, src)
}
func (m *CheckVersionReply) XXX_Size() int {
	return xxx_messageInfo_CheckVersionReply.Size(m)
}
func (m *CheckVersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionReply proto.InternalMessageInfo

func (m *CheckVersionReply) GetIsVersionCompatible() bool {
	if m != nil {
		return m.IsVersionCompatible
	}
	return false
}

type CheckDiskSpaceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckDiskSpaceRequest) Reset()         { *m = CheckDiskSpaceRequest{} }
func (m *CheckDiskSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceRequest) ProtoMessage()    {}
func (*CheckDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{27}
}
func (m *CheckDiskSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceRequest.Unmarshal(m, b)
}
func (m *CheckDiskSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceRequest.Marshal(b, m, deterministic)
}
func (dst *CheckDiskSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceRequest.Merge(dst, src)
}
func (m *CheckDiskSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceRequest.Size(m)
}
func (m *CheckDiskSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceRequest proto.InternalMessageInfo

type CheckDiskSpaceReply struct {
	SegmentFileSysUsage  []string `protobuf:"bytes,1,rep,name=SegmentFileSysUsage,proto3" json:"SegmentFileSysUsage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckDiskSpaceReply) Reset()         { *m = CheckDiskSpaceReply{} }
func (m *CheckDiskSpaceReply) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceReply) ProtoMessage()    {}
func (*CheckDiskSpaceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{28}
}
func (m *CheckDiskSpaceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceReply.Unmarshal(m, b)
}
func (m *CheckDiskSpaceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceReply.Marshal(b, m, deterministic)
}
func (dst *CheckDiskSpaceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceReply.Merge(dst, src)
}
func (m *CheckDiskSpaceReply) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceReply.Size(m)
}
func (m *CheckDiskSpaceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceReply proto.InternalMessageInfo

func (m *CheckDiskSpaceReply) GetSegmentFileSysUsage() []string {
	if m != nil {
		return m.SegmentFileSysUsage
	}
	return nil
}

type PrepareShutdownClustersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareShutdownClustersRequest) Reset()         { *m = PrepareShutdownClustersRequest{} }
func (m *PrepareShutdownClustersRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareShutdownClustersRequest) ProtoMessage()    {}
func (*PrepareShutdownClustersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{29}
}
func (m *PrepareShutdownClustersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareShutdownClustersRequest.Unmarshal(m, b)
}
func (m *PrepareShutdownClustersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareShutdownClustersRequest.Marshal(b, m, deterministic)
}
func (dst *PrepareShutdownClustersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareShutdownClustersRequest.Merge(dst, src)
}
func (m *PrepareShutdownClustersRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareShutdownClustersRequest.Size(m)
}
func (m *PrepareShutdownClustersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareShutdownClustersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareShutdownClustersRequest proto.InternalMessageInfo

type PrepareShutdownClustersReply struct {
	Cluster              WhichCluster `protobuf:"varint,1,opt,name=cluster,proto3,enum=idl.WhichCluster" json:"cluster,omitempty"`
	Succeeded            bool         `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PrepareShutdownClustersReply) Reset()         { *m = PrepareShutdownClustersReply{} }
func (m *PrepareShutdownClustersReply) String() string { return proto.CompactTextString(m) }
func (*PrepareShutdownClustersReply) ProtoMessage()    {}
func (*PrepareShutdownClustersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{30}
}
func (m *PrepareShutdownClustersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareShutdownClustersReply.Unmarshal(m, b)
}
func (m *PrepareShutdownClustersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareShutdownClustersReply.Marshal(b, m, deterministic)
}
func (dst *PrepareShutdownClustersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareShutdownClustersReply.Merge(dst, src)
}
func (m *PrepareShutdownClustersReply) XXX_Size() int {
	return xxx_messageInfo_PrepareShutdownClustersReply.Size(m)
}
func (m *PrepareShutdownClustersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareShutdownClustersReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareShutdownClustersReply proto.InternalMessageInfo

func (m *PrepareShutdownClustersReply) GetCluster() WhichCluster {
	if m != nil {
		return m.Cluster
	}
	return WhichCluster_UNKNOWN
}

func (m *PrepareShutdownClustersReply) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

type PrepareInitClusterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterRequest) Reset()         { *m = PrepareInitClusterRequest{} }
func (m *PrepareInitClusterRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterRequest) ProtoMessage()    {}
func (*PrepareInitClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{31}
}
func (m *PrepareInitClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterRequest.Unmarshal(m, b)
}
func (m *PrepareInitClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterRequest.Marshal(b, m, deterministic)
}
func (dst *PrepareInitClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterRequest.Merge(dst, src)
}
func (m *PrepareInitClusterRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterRequest.Size(m)
}
func (m *PrepareInitClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterRequest proto.InternalMessageInfo

type PrepareInitClusterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterReply) Reset()         { *m = PrepareInitClusterReply{} }
func (m *PrepareInitClusterReply) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterReply) ProtoMessage()    {}
func (*PrepareInitClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{32}
}
func (m *PrepareInitClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterReply.Unmarshal(m, b)
}
func (m *PrepareInitClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterReply.Marshal(b, m, deterministic)
}
func (dst *PrepareInitClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterReply.Merge(dst, src)
}
func (m *PrepareInitClusterReply) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterReply.Size(m)
}
func (m *PrepareInitClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterReply proto.InternalMessageInfo

type UpgradeConvertMasterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeConvertMasterRequest) Reset()         { *m = UpgradeConvertMasterRequest{} }
func (m *UpgradeConvertMasterRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeConvertMasterRequest) ProtoMessage()    {}
func (*UpgradeConvertMasterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{33}
}
func (m *UpgradeConvertMasterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeConvertMasterRequest.Unmarshal(m, b)
}
func (m *UpgradeConvertMasterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeConvertMasterRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradeConvertMasterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeConvertMasterRequest.Merge(dst, src)
}
func (m *UpgradeConvertMasterRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeConvertMasterRequest.Size(m)
}
func (m *UpgradeConvertMasterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeConvertMasterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeConvertMasterRequest proto.InternalMessageInfo

type UpgradeConvertMasterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeConvertMasterReply) Reset()         { *m = UpgradeConvertMasterReply{} }
func (m *UpgradeConvertMasterReply) String() string { return proto.CompactTextString(m) }
func (*UpgradeConvertMasterReply) ProtoMessage()    {}
func (*UpgradeConvertMasterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{34}
}
func (m *UpgradeConvertMasterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeConvertMasterReply.Unmarshal(m, b)
}
func (m *UpgradeConvertMasterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeConvertMasterReply.Marshal(b, m, deterministic)
}
func (dst *UpgradeConvertMasterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeConvertMasterReply.Merge(dst, src)
}
func (m *UpgradeConvertMasterReply) XXX_Size() int {
	return xxx_messageInfo_UpgradeConvertMasterReply.Size(m)
}
func (m *UpgradeConvertMasterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeConvertMasterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeConvertMasterReply proto.InternalMessageInfo

type SetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{35}
}
func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(dst, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetConfigRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetConfigReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigReply) Reset()         { *m = SetConfigReply{} }
func (m *SetConfigReply) String() string { return proto.CompactTextString(m) }
func (*SetConfigReply) ProtoMessage()    {}
func (*SetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{36}
}
func (m *SetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigReply.Unmarshal(m, b)
}
func (m *SetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigReply.Marshal(b, m, deterministic)
}
func (dst *SetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigReply.Merge(dst, src)
}
func (m *SetConfigReply) XXX_Size() int {
	return xxx_messageInfo_SetConfigReply.Size(m)
}
func (m *SetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigReply proto.InternalMessageInfo

type GetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{37}
}
func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(dst, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetConfigReply struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigReply) Reset()         { *m = GetConfigReply{} }
func (m *GetConfigReply) String() string { return proto.CompactTextString(m) }
func (*GetConfigReply) ProtoMessage()    {}
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_to_hub_dccc132a00f5e6f1, []int{38}
}
func (m *GetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReply.Unmarshal(m, b)
}
func (m *GetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReply.Marshal(b, m, deterministic)
}
func (dst *GetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReply.Merge(dst, src)
}
func (m *GetConfigReply) XXX_Size() int {
	return xxx_messageInfo_GetConfigReply.Size(m)
}
func (m *GetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReply proto.InternalMessageInfo

func (m *GetConfigReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*UpgradeReconfigurePortsRequest)(nil), "idl.UpgradeReconfigurePortsRequest")
	proto.RegisterType((*UpgradeReconfigurePortsReply)(nil), "idl.UpgradeReconfigurePortsReply")
	proto.RegisterType((*UpgradeConvertPrimariesRequest)(nil), "idl.UpgradeConvertPrimariesRequest")
	proto.RegisterType((*UpgradeConvertPrimariesReply)(nil), "idl.UpgradeConvertPrimariesReply")
	proto.RegisterType((*UpgradeShareOidsRequest)(nil), "idl.UpgradeShareOidsRequest")
	proto.RegisterType((*UpgradeShareOidsReply)(nil), "idl.UpgradeShareOidsReply")
	proto.RegisterType((*UpgradeValidateStartClusterRequest)(nil), "idl.UpgradeValidateStartClusterRequest")
	proto.RegisterType((*UpgradeValidateStartClusterReply)(nil), "idl.UpgradeValidateStartClusterReply")
	proto.RegisterType((*PingRequest)(nil), "idl.PingRequest")
	proto.RegisterType((*PingReply)(nil), "idl.PingReply")
	proto.RegisterType((*StatusConversionRequest)(nil), "idl.StatusConversionRequest")
	proto.RegisterType((*PrimaryStatus)(nil), "idl.PrimaryStatus")
	proto.RegisterType((*StatusConversionReply)(nil), "idl.StatusConversionReply")
	proto.RegisterType((*StatusUpgradeRequest)(nil), "idl.StatusUpgradeRequest")
	proto.RegisterType((*StatusUpgradeReply)(nil), "idl.StatusUpgradeReply")
	proto.RegisterType((*UpgradeStepStatus)(nil), "idl.UpgradeStepStatus")
	proto.RegisterType((*CheckConfigRequest)(nil), "idl.CheckConfigRequest")
	proto.RegisterType((*CheckConfigReply)(nil), "idl.CheckConfigReply")
	proto.RegisterType((*CheckSeginstallRequest)(nil), "idl.CheckSeginstallRequest")
	proto.RegisterType((*CheckSeginstallReply)(nil), "idl.CheckSeginstallReply")
	proto.RegisterType((*PrepareStartAgentsRequest)(nil), "idl.PrepareStartAgentsRequest")
	proto.RegisterType((*PrepareStartAgentsReply)(nil), "idl.PrepareStartAgentsReply")
	proto.RegisterType((*CountPerDb)(nil), "idl.CountPerDb")
	proto.RegisterType((*CheckObjectCountRequest)(nil), "idl.CheckObjectCountRequest")
	proto.RegisterType((*CheckObjectCountReply)(nil), "idl.CheckObjectCountReply")
	proto.RegisterType((*CheckVersionRequest)(nil), "idl.CheckVersionRequest")
	proto.RegisterType((*CheckVersionReply)(nil), "idl.CheckVersionReply")
	proto.RegisterType((*CheckDiskSpaceRequest)(nil), "idl.CheckDiskSpaceRequest")
	proto.RegisterType((*CheckDiskSpaceReply)(nil), "idl.CheckDiskSpaceReply")
	proto.RegisterType((*PrepareShutdownClustersRequest)(nil), "idl.PrepareShutdownClustersRequest")
	proto.RegisterType((*PrepareShutdownClustersReply)(nil), "idl.PrepareShutdownClustersReply")
	proto.RegisterType((*PrepareInitClusterRequest)(nil), "idl.PrepareInitClusterRequest")
	proto.RegisterType((*PrepareInitClusterReply)(nil), "idl.PrepareInitClusterReply")
	proto.RegisterType((*UpgradeConvertMasterRequest)(nil), "idl.UpgradeConvertMasterRequest")
	proto.RegisterType((*UpgradeConvertMasterReply)(nil), "idl.UpgradeConvertMasterReply")
	proto.RegisterType((*SetConfigRequest)(nil), "idl.SetConfigRequest")
	proto.RegisterType((*SetConfigReply)(nil), "idl.SetConfigReply")
	proto.RegisterType((*GetConfigRequest)(nil), "idl.GetConfigRequest")
	proto.RegisterType((*GetConfigReply)(nil), "idl.GetConfigReply")
	proto.RegisterEnum("idl.UpgradeSteps", UpgradeSteps_name, UpgradeSteps_value)
	proto.RegisterEnum("idl.StepStatus", StepStatus_name, StepStatus_value)
	proto.RegisterEnum("idl.WhichCluster", WhichCluster_name, WhichCluster_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CliToHubClient is the client API for CliToHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CliToHubClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	StatusUpgrade(ctx context.Context, in *StatusUpgradeRequest, opts ...grpc.CallOption) (*StatusUpgradeReply, error)
	StatusConversion(ctx context.Context, in *StatusConversionRequest, opts ...grpc.CallOption) (*StatusConversionReply, error)
	CheckConfig(ctx context.Context, in *CheckConfigRequest, opts ...grpc.CallOption) (*CheckConfigReply, error)
	CheckSeginstall(ctx context.Context, in *CheckSeginstallRequest, opts ...grpc.CallOption) (*CheckSeginstallReply, error)
	CheckObjectCount(ctx context.Context, in *CheckObjectCountRequest, opts ...grpc.CallOption) (*CheckObjectCountReply, error)
	CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionReply, error)
	CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error)
	PrepareInitCluster(ctx context.Context, in *PrepareInitClusterRequest, opts ...grpc.CallOption) (*PrepareInitClusterReply, error)
	PrepareShutdownClusters(ctx context.Context, in *PrepareShutdownClustersRequest, opts ...grpc.CallOption) (CliToHub_PrepareShutdownClustersClient, error)
	UpgradeConvertMaster(ctx context.Context, in *UpgradeConvertMasterRequest, opts ...grpc.CallOption) (*UpgradeConvertMasterReply, error)
	PrepareStartAgents(ctx context.Context, in *PrepareStartAgentsRequest, opts ...grpc.CallOption) (*PrepareStartAgentsReply, error)
	UpgradeShareOids(ctx context.Context, in *UpgradeShareOidsRequest, opts ...grpc.CallOption) (*UpgradeShareOidsReply, error)
	UpgradeValidateStartCluster(ctx context.Context, in *UpgradeValidateStartClusterRequest, opts ...grpc.CallOption) (*UpgradeValidateStartClusterReply, error)
	UpgradeConvertPrimaries(ctx context.Context, in *UpgradeConvertPrimariesRequest, opts ...grpc.CallOption) (*UpgradeConvertPrimariesReply, error)
	UpgradeReconfigurePorts(ctx context.Context, in *UpgradeReconfigurePortsRequest, opts ...grpc.CallOption) (*UpgradeReconfigurePortsReply, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
}

type cliToHubClient struct {
	cc *grpc.ClientConn
}

func NewCliToHubClient(cc *grpc.ClientConn) CliToHubClient {
	return &cliToHubClient{cc}
}

func (c *cliToHubClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) StatusUpgrade(ctx context.Context, in *StatusUpgradeRequest, opts ...grpc.CallOption) (*StatusUpgradeReply, error) {
	out := new(StatusUpgradeReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/StatusUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) StatusConversion(ctx context.Context, in *StatusConversionRequest, opts ...grpc.CallOption) (*StatusConversionReply, error) {
	out := new(StatusConversionReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/StatusConversion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckConfig(ctx context.Context, in *CheckConfigRequest, opts ...grpc.CallOption) (*CheckConfigReply, error) {
	out := new(CheckConfigReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckSeginstall(ctx context.Context, in *CheckSeginstallRequest, opts ...grpc.CallOption) (*CheckSeginstallReply, error) {
	out := new(CheckSeginstallReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckSeginstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckObjectCount(ctx context.Context, in *CheckObjectCountRequest, opts ...grpc.CallOption) (*CheckObjectCountReply, error) {
	out := new(CheckObjectCountReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckObjectCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionReply, error) {
	out := new(CheckVersionReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error) {
	out := new(CheckDiskSpaceReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckDiskSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) PrepareInitCluster(ctx context.Context, in *PrepareInitClusterRequest, opts ...grpc.CallOption) (*PrepareInitClusterReply, error) {
	out := new(PrepareInitClusterReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/PrepareInitCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) PrepareShutdownClusters(ctx context.Context, in *PrepareShutdownClustersRequest, opts ...grpc.CallOption) (CliToHub_PrepareShutdownClustersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[0], "/idl.CliToHub/PrepareShutdownClusters", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubPrepareShutdownClustersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_PrepareShutdownClustersClient interface {
	Recv() (*PrepareShutdownClustersReply, error)
	grpc.ClientStream
}

type cliToHubPrepareShutdownClustersClient struct {
	grpc.ClientStream
}

func (x *cliToHubPrepareShutdownClustersClient) Recv() (*PrepareShutdownClustersReply, error) {
	m := new(PrepareShutdownClustersReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) UpgradeConvertMaster(ctx context.Context, in *UpgradeConvertMasterRequest, opts ...grpc.CallOption) (*UpgradeConvertMasterReply, error) {
	out := new(UpgradeConvertMasterReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/UpgradeConvertMaster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) PrepareStartAgents(ctx context.Context, in *PrepareStartAgentsRequest, opts ...grpc.CallOption) (*PrepareStartAgentsReply, error) {
	out := new(PrepareStartAgentsReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/PrepareStartAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) UpgradeShareOids(ctx context.Context, in *UpgradeShareOidsRequest, opts ...grpc.CallOption) (*UpgradeShareOidsReply, error) {
	out := new(UpgradeShareOidsReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/UpgradeShareOids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) UpgradeValidateStartCluster(ctx context.Context, in *UpgradeValidateStartClusterRequest, opts ...grpc.CallOption) (*UpgradeValidateStartClusterReply, error) {
	out := new(UpgradeValidateStartClusterReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/UpgradeValidateStartCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) UpgradeConvertPrimaries(ctx context.Context, in *UpgradeConvertPrimariesRequest, opts ...grpc.CallOption) (*UpgradeConvertPrimariesReply, error) {
	out := new(UpgradeConvertPrimariesReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/UpgradeConvertPrimaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) UpgradeReconfigurePorts(ctx context.Context, in *UpgradeReconfigurePortsRequest, opts ...grpc.CallOption) (*UpgradeReconfigurePortsReply, error) {
	out := new(UpgradeReconfigurePortsReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/UpgradeReconfigurePorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error) {
	out := new(SetConfigReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	out := new(GetConfigReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CliToHubServer is the server API for CliToHub service.
type CliToHubServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	StatusUpgrade(context.Context, *StatusUpgradeRequest) (*StatusUpgradeReply, error)
	StatusConversion(context.Context, *StatusConversionRequest) (*StatusConversionReply, error)
	CheckConfig(context.Context, *CheckConfigRequest) (*CheckConfigReply, error)
	CheckSeginstall(context.Context, *CheckSeginstallRequest) (*CheckSeginstallReply, error)
	CheckObjectCount(context.Context, *CheckObjectCountRequest) (*CheckObjectCountReply, error)
	CheckVersion(context.Context, *CheckVersionRequest) (*CheckVersionReply, error)
	CheckDiskSpace(context.Context, *CheckDiskSpaceRequest) (*CheckDiskSpaceReply, error)
	PrepareInitCluster(context.Context, *PrepareInitClusterRequest) (*PrepareInitClusterReply, error)
	PrepareShutdownClusters(*PrepareShutdownClustersRequest, CliToHub_PrepareShutdownClustersServer) error
	UpgradeConvertMaster(context.Context, *UpgradeConvertMasterRequest) (*UpgradeConvertMasterReply, error)
	PrepareStartAgents(context.Context, *PrepareStartAgentsRequest) (*PrepareStartAgentsReply, error)
	UpgradeShareOids(context.Context, *UpgradeShareOidsRequest) (*UpgradeShareOidsReply, error)
	UpgradeValidateStartCluster(context.Context, *UpgradeValidateStartClusterRequest) (*UpgradeValidateStartClusterReply, error)
	UpgradeConvertPrimaries(context.Context, *UpgradeConvertPrimariesRequest) (*UpgradeConvertPrimariesReply, error)
	UpgradeReconfigurePorts(context.Context, *UpgradeReconfigurePortsRequest) (*UpgradeReconfigurePortsReply, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigReply, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
}

func RegisterCliToHubServer(s *grpc.Server, srv CliToHubServer) {
	s.RegisterService(&_CliToHub_serviceDesc, srv)
}

func _CliToHub_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_StatusUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).StatusUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/StatusUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).StatusUpgrade(ctx, req.(*StatusUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_StatusConversion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).StatusConversion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/StatusConversion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).StatusConversion(ctx, req.(*StatusConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckConfig(ctx, req.(*CheckConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckSeginstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSeginstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckSeginstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckSeginstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckSeginstall(ctx, req.(*CheckSeginstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckObjectCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckObjectCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckObjectCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckObjectCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckObjectCount(ctx, req.(*CheckObjectCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckVersion(ctx, req.(*CheckVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDiskSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckDiskSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckDiskSpace(ctx, req.(*CheckDiskSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_PrepareInitCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareInitClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).PrepareInitCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/PrepareInitCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).PrepareInitCluster(ctx, req.(*PrepareInitClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_PrepareShutdownClusters_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrepareShutdownClustersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).PrepareShutdownClusters(m, &cliToHubPrepareShutdownClustersServer{stream})
}

type CliToHub_PrepareShutdownClustersServer interface {
	Send(*PrepareShutdownClustersReply) error
	grpc.ServerStream
}

type cliToHubPrepareShutdownClustersServer struct {
	grpc.ServerStream
}

func (x *cliToHubPrepareShutdownClustersServer) Send(m *PrepareShutdownClustersReply) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_UpgradeConvertMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeConvertMasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).UpgradeConvertMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/UpgradeConvertMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).UpgradeConvertMaster(ctx, req.(*UpgradeConvertMasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_PrepareStartAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareStartAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).PrepareStartAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/PrepareStartAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).PrepareStartAgents(ctx, req.(*PrepareStartAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_UpgradeShareOids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeShareOidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).UpgradeShareOids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/UpgradeShareOids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).UpgradeShareOids(ctx, req.(*UpgradeShareOidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_UpgradeValidateStartCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeValidateStartClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).UpgradeValidateStartCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/UpgradeValidateStartCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).UpgradeValidateStartCluster(ctx, req.(*UpgradeValidateStartClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_UpgradeConvertPrimaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeConvertPrimariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).UpgradeConvertPrimaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/UpgradeConvertPrimaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).UpgradeConvertPrimaries(ctx, req.(*UpgradeConvertPrimariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_UpgradeReconfigurePorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeReconfigurePortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).UpgradeReconfigurePorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/UpgradeReconfigurePorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).UpgradeReconfigurePorts(ctx, req.(*UpgradeReconfigurePortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CliToHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.CliToHub",
	HandlerType: (*CliToHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CliToHub_Ping_Handler,
		},
		{
			MethodName: "StatusUpgrade",
			Handler:    _CliToHub_StatusUpgrade_Handler,
		},
		{
			MethodName: "StatusConversion",
			Handler:    _CliToHub_StatusConversion_Handler,
		},
		{
			MethodName: "CheckConfig",
			Handler:    _CliToHub_CheckConfig_Handler,
		},
		{
			MethodName: "CheckSeginstall",
			Handler:    _CliToHub_CheckSeginstall_Handler,
		},
		{
			MethodName: "CheckObjectCount",
			Handler:    _CliToHub_CheckObjectCount_Handler,
		},
		{
			MethodName: "CheckVersion",
			Handler:    _CliToHub_CheckVersion_Handler,
		},
		{
			MethodName: "CheckDiskSpace",
			Handler:    _CliToHub_CheckDiskSpace_Handler,
		},
		{
			MethodName: "PrepareInitCluster",
			Handler:    _CliToHub_PrepareInitCluster_Handler,
		},
		{
			MethodName: "UpgradeConvertMaster",
			Handler:    _CliToHub_UpgradeConvertMaster_Handler,
		},
		{
			MethodName: "PrepareStartAgents",
			Handler:    _CliToHub_PrepareStartAgents_Handler,
		},
		{
			MethodName: "UpgradeShareOids",
			Handler:    _CliToHub_UpgradeShareOids_Handler,
		},
		{
			MethodName: "UpgradeValidateStartCluster",
			Handler:    _CliToHub_UpgradeValidateStartCluster_Handler,
		},
		{
			MethodName: "UpgradeConvertPrimaries",
			Handler:    _CliToHub_UpgradeConvertPrimaries_Handler,
		},
		{
			MethodName: "UpgradeReconfigurePorts",
			Handler:    _CliToHub_UpgradeReconfigurePorts_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _CliToHub_SetConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _CliToHub_GetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrepareShutdownClusters",
			Handler:       _CliToHub_PrepareShutdownClusters_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cli_to_hub.proto",
}

func init() { proto.RegisterFile("cli_to_hub.proto", fileDescriptor_cli_to_hub_dccc132a00f5e6f1) }

var fileDescriptor_cli_to_hub_dccc132a00f5e6f1 = []byte{
	// 1281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0x8e, 0x93, 0x34, 0x89, 0xcf, 0xae, 0xab, 0xb0, 0x89, 0x63, 0x2b, 0x59, 0x90, 0x69, 0x6b,
	0x1b, 0x64, 0x40, 0x51, 0xb4, 0xc0, 0x80, 0x01, 0x03, 0x06, 0x55, 0x56, 0x1c, 0xa3, 0x8e, 0x6c,
	0x50, 0x72, 0x0a, 0x6c, 0x03, 0x0c, 0x59, 0x66, 0x1d, 0xb5, 0x8a, 0xe4, 0x49, 0x74, 0x87, 0x7c,
	0xdd, 0xbf, 0xd9, 0x0f, 0xdb, 0xff, 0x18, 0x28, 0xea, 0x5d, 0xb2, 0xb7, 0x6f, 0xe2, 0x3d, 0xf7,
	0xc2, 0xe3, 0x9d, 0x9e, 0x23, 0x41, 0xb0, 0x1c, 0x7b, 0x4a, 0xbd, 0xe9, 0xfd, 0x6a, 0xf6, 0x7a,
	0xe9, 0x7b, 0xd4, 0x43, 0x3b, 0xf6, 0xdc, 0x91, 0x2e, 0xe0, 0x7c, 0xb2, 0x5c, 0xf8, 0xe6, 0x9c,
	0x60, 0x62, 0x79, 0xee, 0x27, 0x7b, 0xb1, 0xf2, 0xc9, 0xd8, 0xf3, 0x69, 0x80, 0xc9, 0x1f, 0x2b,
	0x12, 0x50, 0xe9, 0x1c, 0xce, 0xd6, 0x6a, 0x2c, 0x9d, 0xc7, 0x8c, 0x07, 0xc5, 0x73, 0xbf, 0x12,
	0x9f, 0x8e, 0x7d, 0xfb, 0xc1, 0xf4, 0x6d, 0x52, 0xe1, 0xa1, 0xac, 0xc1, 0x3c, 0x74, 0xe1, 0x24,
	0xc2, 0xf5, 0x7b, 0xd3, 0x27, 0x23, 0x7b, 0x9e, 0x98, 0x9e, 0xc0, 0x71, 0x19, 0x62, 0x36, 0xdf,
	0x83, 0x14, 0x01, 0x77, 0xa6, 0x63, 0xcf, 0x4d, 0x4a, 0x74, 0x6a, 0xfa, 0x54, 0x71, 0x56, 0x01,
	0x25, 0x7e, 0x6c, 0x2e, 0xc1, 0xc5, 0x46, 0x2d, 0xe6, 0xe9, 0x29, 0x34, 0xc6, 0xb6, 0xbb, 0x88,
	0x4d, 0x1a, 0x50, 0xe7, 0xcb, 0x68, 0x67, 0x3a, 0x35, 0xe9, 0x2a, 0xe0, 0x1b, 0x0f, 0x6c, 0xcf,
	0x8d, 0xf5, 0xfe, 0xaa, 0xc1, 0x53, 0x9e, 0xc7, 0x23, 0x57, 0x41, 0xaf, 0x60, 0x8f, 0x7f, 0x75,
	0x6a, 0x17, 0xb5, 0xcb, 0xd6, 0xdb, 0x67, 0xaf, 0xed, 0xb9, 0xf3, 0x5a, 0xa7, 0x64, 0xc9, 0xc5,
	0x38, 0x82, 0x11, 0x82, 0xdd, 0xde, 0xcc, 0x9e, 0x77, 0xb6, 0x2f, 0x6a, 0x97, 0x4f, 0x70, 0xf8,
	0x8d, 0x3a, 0xb0, 0xaf, 0x78, 0x2e, 0x25, 0x2e, 0xed, 0xec, 0x84, 0xe2, 0x78, 0x89, 0x44, 0x38,
	0xb8, 0xf1, 0x02, 0xea, 0x9a, 0x0f, 0xa4, 0xb3, 0x7b, 0x51, 0xbb, 0xac, 0xe3, 0x64, 0x2d, 0xfd,
	0x06, 0xc7, 0xe5, 0xfd, 0x2d, 0x9d, 0x47, 0xf4, 0x1e, 0x90, 0x95, 0x88, 0xb8, 0x0a, 0x61, 0xfb,
	0xda, 0xb9, 0x6c, 0xbc, 0x45, 0xe1, 0xbe, 0x72, 0x7b, 0xc7, 0x15, 0xda, 0x52, 0x1b, 0x8e, 0xf8,
	0x77, 0x52, 0x7e, 0x9e, 0xf9, 0x67, 0x40, 0x05, 0x39, 0x8b, 0x68, 0x40, 0xd7, 0xb1, 0x03, 0x3a,
	0xfa, 0x14, 0xd7, 0x2b, 0xc9, 0x3b, 0x09, 0xdc, 0x0e, 0x03, 0x97, 0x70, 0xbc, 0xde, 0x50, 0xb2,
	0xe0, 0xb0, 0x24, 0x46, 0x2f, 0x60, 0x37, 0xa0, 0x64, 0x19, 0x1d, 0xf3, 0x61, 0xd1, 0x6b, 0x80,
	0x43, 0x98, 0xd5, 0x23, 0xe0, 0xf5, 0xd8, 0x5e, 0x53, 0x0f, 0x0e, 0x4b, 0x47, 0x80, 0x94, 0x7b,
	0x62, 0x7d, 0x51, 0xc2, 0xee, 0x8e, 0xd3, 0xfc, 0x11, 0x84, 0x9c, 0x94, 0x25, 0x29, 0x41, 0x93,
	0x2f, 0x33, 0x85, 0xae, 0xe3, 0x9c, 0x4c, 0xea, 0x40, 0x3b, 0xb4, 0xd3, 0xc9, 0xc2, 0x76, 0x03,
	0x6a, 0x3a, 0x4e, 0xec, 0xb1, 0x0d, 0x47, 0x25, 0x84, 0x75, 0xd9, 0x29, 0x74, 0xc7, 0x3e, 0x59,
	0x9a, 0x3e, 0xef, 0x4e, 0x79, 0x41, 0xdc, 0xf4, 0xf7, 0xeb, 0xc2, 0x49, 0x15, 0xc8, 0xec, 0x7e,
	0x07, 0x50, 0xbc, 0x95, 0x4b, 0xc7, 0xc4, 0xef, 0xcd, 0x50, 0x1b, 0xf6, 0x7a, 0x33, 0x8d, 0x75,
	0x09, 0xdf, 0x55, 0xb4, 0x62, 0x9d, 0x25, 0x7b, 0xa1, 0x5e, 0xd4, 0x70, 0xf1, 0x12, 0x9d, 0x41,
	0xfd, 0x86, 0x98, 0x4b, 0x8e, 0xf1, 0xae, 0x4b, 0x05, 0x2c, 0x70, 0xb8, 0xdb, 0xd1, 0xec, 0x33,
	0xb1, 0x68, 0x28, 0x8b, 0xf7, 0x34, 0x84, 0xe3, 0x32, 0xc4, 0xce, 0xe7, 0x1d, 0x34, 0x87, 0x61,
	0x2d, 0x43, 0x59, 0x5c, 0x77, 0x7e, 0xf0, 0xe9, 0x56, 0x71, 0x4e, 0x49, 0x3a, 0x86, 0xe7, 0xa1,
	0xb7, 0xbb, 0xfc, 0x0f, 0xa6, 0xc2, 0x61, 0x5e, 0xcc, 0x02, 0xbc, 0x81, 0xe7, 0x83, 0x20, 0x92,
	0x28, 0xde, 0xc3, 0xd2, 0xa4, 0xf6, 0xcc, 0xe1, 0x19, 0x1f, 0xe0, 0x2a, 0x88, 0x31, 0x48, 0xe8,
	0xa6, 0x67, 0x07, 0x5f, 0xf4, 0xa5, 0x69, 0x25, 0x6d, 0xdc, 0x8f, 0xc2, 0x66, 0x80, 0x28, 0x82,
	0x4e, 0x16, 0x0f, 0xc4, 0xa5, 0xd7, 0xb6, 0x43, 0xf4, 0xc7, 0x60, 0x12, 0x98, 0x0b, 0x12, 0x66,
	0x52, 0xc7, 0x55, 0x10, 0x23, 0xc0, 0xb8, 0x42, 0xf7, 0x2b, 0x3a, 0xf7, 0xfe, 0x74, 0x23, 0x7e,
	0x49, 0x6a, 0x68, 0xc3, 0xd9, 0x5a, 0x0d, 0x16, 0xf3, 0x07, 0xd8, 0xb7, 0xb8, 0x20, 0xd7, 0xd3,
	0x1f, 0xef, 0x6d, 0xeb, 0x3e, 0xe6, 0xaa, 0x58, 0x83, 0x55, 0x2d, 0x58, 0x59, 0x16, 0x21, 0x73,
	0xc2, 0x29, 0xe4, 0x00, 0xa7, 0x82, 0x4c, 0x2f, 0x0d, 0x5c, 0xbb, 0x48, 0x87, 0x69, 0x2f, 0xe5,
	0x40, 0xd6, 0x4b, 0xdf, 0xc0, 0x69, 0x9e, 0xa3, 0x6f, 0xcd, 0xac, 0xe5, 0x29, 0x74, 0xab, 0x61,
	0x66, 0xfb, 0x33, 0x08, 0x3a, 0xa1, 0xb9, 0xbf, 0x87, 0x71, 0x9c, 0x9b, 0xf6, 0x62, 0xf8, 0x8d,
	0x8e, 0xe0, 0xc9, 0x57, 0xd3, 0x59, 0x91, 0x70, 0xd7, 0x75, 0xcc, 0x17, 0x92, 0x00, 0xad, 0x8c,
	0x35, 0xf3, 0xf7, 0x12, 0x84, 0xfe, 0xff, 0xf0, 0x27, 0xbd, 0x84, 0x56, 0x3f, 0x67, 0x99, 0x46,
	0xa8, 0x65, 0x22, 0x5c, 0xfd, 0x53, 0x83, 0x66, 0x96, 0x1f, 0x90, 0x00, 0xcd, 0x89, 0xf6, 0x41,
	0x1b, 0x7d, 0xd4, 0xa6, 0xba, 0xa1, 0x8e, 0x85, 0x2d, 0x04, 0xb0, 0xa7, 0x8c, 0xb4, 0xeb, 0x41,
	0x5f, 0xa8, 0xa1, 0x16, 0x80, 0xae, 0xf6, 0x07, 0x9a, 0x6e, 0xc8, 0xc3, 0xa1, 0xb0, 0xcd, 0xb4,
	0x75, 0x43, 0xc6, 0xc6, 0x54, 0xee, 0xab, 0x9a, 0xa1, 0x0b, 0x3b, 0x4c, 0x32, 0xd0, 0x06, 0xc6,
	0x54, 0x19, 0x4e, 0x74, 0x43, 0xc5, 0xc2, 0x2e, 0x3a, 0x86, 0x43, 0xfd, 0x66, 0x62, 0xf4, 0x98,
	0xcb, 0x48, 0xaa, 0x0b, 0x4f, 0x10, 0x82, 0x96, 0x32, 0xd2, 0xee, 0x54, 0x6c, 0x4c, 0x6f, 0xe5,
	0x50, 0x75, 0x2f, 0x74, 0x7f, 0x23, 0x63, 0x75, 0x3a, 0x1a, 0xf4, 0x74, 0x61, 0x9f, 0x99, 0xc6,
	0x3a, 0x63, 0x3c, 0xb8, 0x95, 0xf1, 0x40, 0xd5, 0x85, 0x03, 0x24, 0x42, 0xfb, 0x4e, 0x1e, 0x0e,
	0x7a, 0xb2, 0xa1, 0x4e, 0x79, 0xf8, 0x38, 0x5a, 0x9d, 0x99, 0x60, 0x95, 0xef, 0x77, 0x82, 0xd5,
	0xe9, 0x78, 0x84, 0x0d, 0x5d, 0x80, 0x2b, 0x03, 0x20, 0xc3, 0x92, 0x08, 0x5a, 0x69, 0x92, 0xb2,
	0x31, 0xd1, 0x85, 0x2d, 0xd4, 0x80, 0xfd, 0xb1, 0xaa, 0xf5, 0x06, 0x1a, 0xcb, 0xb3, 0x01, 0xfb,
	0x78, 0xa2, 0x69, 0x6c, 0xb1, 0x8d, 0x9a, 0x70, 0xa0, 0x8c, 0x6e, 0xc7, 0x43, 0xd5, 0x50, 0x85,
	0x1d, 0x76, 0x1c, 0xd7, 0xf2, 0x60, 0xa8, 0xf6, 0x84, 0xdd, 0xab, 0x77, 0xd0, 0xcc, 0x36, 0x22,
	0x33, 0x8b, 0xfc, 0xf2, 0x73, 0xd3, 0x47, 0x13, 0xac, 0xa8, 0x42, 0x8d, 0x7d, 0x1b, 0x32, 0xee,
	0xab, 0x86, 0xb0, 0xfd, 0xf6, 0xef, 0x06, 0x1c, 0x28, 0x8e, 0x6d, 0x78, 0x37, 0xab, 0x19, 0xba,
	0x82, 0x5d, 0x36, 0x52, 0x91, 0xc0, 0x07, 0x4f, 0x3a, 0x6c, 0xc5, 0x56, 0x46, 0xc2, 0x2a, 0xbf,
	0x85, 0x54, 0x78, 0x9a, 0x1b, 0x2e, 0xa8, 0x1b, 0xb1, 0x76, 0x79, 0x10, 0x89, 0x27, 0x55, 0x10,
	0x77, 0xa3, 0x81, 0x50, 0x1c, 0x8c, 0xe8, 0x2c, 0xa3, 0x5e, 0x9a, 0xe7, 0xa2, 0xb8, 0x06, 0xe5,
	0xfe, 0x7e, 0x81, 0x46, 0x66, 0x18, 0x20, 0x1e, 0xb9, 0x3c, 0x34, 0xc4, 0xe3, 0x32, 0xc0, 0x1d,
	0x7c, 0x80, 0x67, 0x05, 0xee, 0x47, 0xa7, 0xa9, 0x6e, 0x69, 0x56, 0x88, 0xdd, 0x6a, 0x30, 0xc9,
	0xae, 0xc8, 0xbf, 0x51, 0x76, 0x6b, 0x18, 0x3b, 0xca, 0xae, 0x92, 0xb4, 0xa5, 0x2d, 0xf4, 0x1e,
	0x9a, 0x59, 0xaa, 0x45, 0x9d, 0x54, 0x3b, 0x4f, 0xca, 0x62, 0xbb, 0x02, 0xe1, 0x3e, 0x6e, 0xa0,
	0x95, 0xa7, 0x53, 0x94, 0x89, 0x59, 0x24, 0x5f, 0xb1, 0x53, 0x89, 0x71, 0x4f, 0x06, 0xa0, 0x32,
	0x4b, 0xa1, 0xf3, 0xe8, 0xd6, 0xb2, 0x86, 0xdb, 0xc4, 0xb3, 0xb5, 0x38, 0xf7, 0x4a, 0xd2, 0x39,
	0x5a, 0xe0, 0x60, 0xf4, 0x5d, 0xd6, 0x74, 0x0d, 0x87, 0x8b, 0xdf, 0x6e, 0x56, 0x0a, 0x83, 0xbc,
	0xa9, 0xa1, 0x5f, 0xe1, 0xa8, 0x8a, 0x28, 0xd1, 0x45, 0xf6, 0x96, 0x52, 0x45, 0xb1, 0xe2, 0xf9,
	0x06, 0x8d, 0xe2, 0xc1, 0x64, 0xae, 0x02, 0xf9, 0x83, 0x29, 0x5f, 0x20, 0xf2, 0x07, 0x53, 0xba,
	0x43, 0x84, 0xcd, 0x54, 0xbc, 0x62, 0x47, 0xcd, 0xb4, 0xe6, 0x52, 0x1e, 0x35, 0x53, 0xf5, 0xbd,
	0x7c, 0x0b, 0x79, 0xc9, 0x24, 0xa9, 0xba, 0x73, 0xa3, 0x57, 0x59, 0xe3, 0x0d, 0x77, 0x77, 0xf1,
	0xc5, 0x7f, 0x2b, 0xf2, 0x80, 0x56, 0xf2, 0x7c, 0x28, 0x3e, 0x2f, 0xa2, 0xca, 0x6e, 0x7e, 0x9e,
	0x44, 0x95, 0xdd, 0xf8, 0x42, 0xc9, 0x06, 0x29, 0xbe, 0x82, 0xf2, 0x41, 0xd6, 0xbc, 0xa2, 0xf2,
	0x41, 0xaa, 0x1f, 0x52, 0x5b, 0xe8, 0x27, 0xa8, 0x27, 0xa3, 0x10, 0x71, 0x2a, 0x29, 0x0e, 0x56,
	0xf1, 0x79, 0x51, 0x9c, 0x98, 0xf6, 0x0b, 0xa6, 0xfd, 0x6a, 0xd3, 0x7e, 0xc1, 0x74, 0xb6, 0x17,
	0x3e, 0x07, 0xdf, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x2c, 0xf4, 0x3c, 0x22, 0x0e, 0x00,
	0x00,
}
